"""Is a shift-by-matmul causal conv actually cheaper than the slice FIR?

Asked before building a kernel, because the kernel's whole premise is that a row
shift can be done without leaving TILE layout, and that the matmul which replaces
the shift is cheap. Both halves are assumptions until measured.

THE TRAP THIS IS CHECKING FOR. A shift of the whole sequence, S[T,T] @ x[T,C], is
O(T^2 C): at T=2048, C=5120 that is 21 GFLOP per tap, far worse than the layout it
replaces. It is only cheap done per tile-row, S[32,32] @ x_i[32,C], which is
O(T*32*C) - 671 MFLOP per tap at these shapes, about 200 us of arithmetic for all
four taps against the 1152 us of layout the FIR spends. If ttnn cannot express the
batched form the kernel premise is weaker than claimed, and that is worth knowing
for the price of one probe rather than a day of kernel work.

THE ARMS.

  fir     what the model does now: concat the carry, then K-1 sub-tile row slices,
          each forcing untilize/slice/tilize over the whole activation, and a mac
  shift   reshape to tile-rows, batched matmul by a fixed banded 32x32 matrix, a
          tap broadcast-multiply and a sum - never leaving TILE

Correctness is checked as well as speed. An arm that is fast and wrong is not a
result, and the shift matrices are generated by the same code the reference test
pins, so a disagreement here means the ttnn composition is wrong rather than the
maths.

Every ttnn call that might not exist in this build is guarded, so a missing API is
recorded rather than costing the hardware slot.
"""

import argparse
import io
import json
import os
import time
import traceback

BEGIN = '<<<SHIFT_MM_JSON_BEGIN>>>'
END = '<<<SHIFT_MM_JSON_END>>>'
TILE = 32


def shift_matrices(torch, k):
    """S_self[j], S_prev[j] so that (S_prev[j] @ prev + S_self[j] @ cur)[r] == xin[r+j]."""
    self_m, prev_m = [], []
    for j in range(k):
        s = torch.zeros(TILE, TILE)
        p = torch.zeros(TILE, TILE)
        for r in range(TILE):
            src = r + j - (k - 1)
            if src >= 0:
                s[r, src] = 1.0
            else:
                p[r, TILE + src] = 1.0
        self_m.append(s)
        prev_m.append(p)
    return self_m, prev_m


def timed(fn, iters, sync):
    fn()
    sync()
    start = time.time()
    for _ in range(iters):
        out = fn()
    sync()
    return (time.time() - start) / iters, out


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--rows', type=int, default=2048)
    parser.add_argument('--cols', type=int, default=5120)
    parser.add_argument('--taps', type=int, default=4)
    parser.add_argument('--iters', type=int, default=20)
    parser.add_argument('--json')
    options = parser.parse_args()

    report = {'rows': options.rows, 'cols': options.cols, 'taps': options.taps,
              'iters': options.iters}
    try:
        import torch

        from feature_projection import require_projection_environment
        require_projection_environment(os.environ, True)
        import ttnn

        T, C, K = options.rows, options.cols, options.taps
        NT = T // TILE
        report['tile_rows'] = NT

        mesh = ttnn.open_mesh_device(ttnn.MeshShape(1, 2), l1_small_size=24576)
        try:
            def sync():
                ttnn.synchronize_device(mesh)

            replicate = ttnn.ReplicateTensorToMesh(mesh)

            def dev(t):
                return ttnn.from_torch(t.to(torch.bfloat16), dtype=ttnn.bfloat16,
                                       layout=ttnn.TILE_LAYOUT, device=mesh,
                                       memory_config=ttnn.DRAM_MEMORY_CONFIG,
                                       mesh_mapper=replicate)

            torch.manual_seed(0)
            x_host = torch.randn(1, T, C)
            carry_host = torch.zeros(1, K - 1, C)
            taps_host = [torch.randn(1, 1, C) * 0.5 for _ in range(K)]

            x = dev(x_host)
            taps = [dev(t) for t in taps_host]

            # ---- arm 1: the slice FIR, which is what the model runs today ----
            xin_host = torch.cat([carry_host, x_host], dim=1)
            xin = dev(xin_host)

            def fir():
                acc = None
                for j in range(K):
                    # a sub-tile row window: this is the slice that forces the
                    # untilize/slice/tilize round-trip
                    win = ttnn.slice(xin, (0, j, 0), (1, j + T, C))
                    term = ttnn.multiply(win, taps[j])
                    acc = term if acc is None else ttnn.add(acc, term)
                    ttnn.deallocate(win)
                return ttnn.silu(acc)

            try:
                fir_s, fir_out = timed(fir, options.iters, sync)
                report['fir_ms'] = round(1e3 * fir_s, 3)
            except BaseException as error:
                report['fir_error'] = '%s: %s' % (type(error).__name__, str(error)[:220])
                fir_out = None

            # ---- arm 2: shift by batched matmul, never leaving TILE ----
            self_h, prev_h = shift_matrices(torch, K)
            # [1, 1, 32, 32] so the batched matmul can broadcast it over tile-rows
            self_m = [dev(m.reshape(1, TILE, TILE)) for m in self_h]
            prev_m = [dev(m.reshape(1, TILE, TILE)) for m in prev_h]

            # x as tile-rows. A reshape on a tile boundary is a view, not a re-layout.
            try:
                x_rows = ttnn.reshape(x, (NT, TILE, C))
                report['reshape_to_tile_rows'] = 'ok'
            except BaseException as error:
                report['reshape_to_tile_rows'] = '%s: %s' % (type(error).__name__,
                                                             str(error)[:200])
                x_rows = None

            if x_rows is not None:
                # prev_rows[i] is tile-row i-1, and zeros for i == 0 because the carry
                # is zero here. Built with a WHOLE-TILE concat and slice, which are
                # tile-aligned and so should need no layout change - that is the whole
                # point: only sub-tile shifts are expensive.
                zero_row = dev(torch.zeros(1, TILE, C))

                def shift_arm():
                    head = ttnn.slice(x_rows, (0, 0, 0), (NT - 1, TILE, C))
                    prev_rows = ttnn.concat([zero_row, head], dim=0)
                    acc = None
                    for j in range(K):
                        cur_part = ttnn.matmul(self_m[j], x_rows)
                        prev_part = ttnn.matmul(prev_m[j], prev_rows)
                        shifted = ttnn.add(cur_part, prev_part)
                        term = ttnn.multiply(shifted, taps[j])
                        acc = term if acc is None else ttnn.add(acc, term)
                        for dead in (cur_part, prev_part, shifted):
                            ttnn.deallocate(dead)
                    ttnn.deallocate(head)
                    ttnn.deallocate(prev_rows)
                    return ttnn.silu(acc)

                try:
                    shift_s, shift_out = timed(shift_arm, options.iters, sync)
                    report['shift_ms'] = round(1e3 * shift_s, 3)
                except BaseException as error:
                    report['shift_error'] = '%s: %s' % (type(error).__name__,
                                                        str(error)[:220])
                    shift_out = None
            else:
                shift_out = None

            # An arm that is fast and wrong is not a result. The first draft of this
            # probe computed prev_rows and never added it, which would have reported a
            # speedup for a conv missing its cross-tile term.
            if fir_out is not None and shift_out is not None:
                try:
                    a = ttnn.to_torch(fir_out, mesh_composer=ttnn.ConcatMeshToTensor(mesh, dim=0))
                    b = ttnn.to_torch(shift_out, mesh_composer=ttnn.ConcatMeshToTensor(mesh, dim=0))
                    a = a.float().flatten()[:T * C]
                    b = b.float().flatten()[:T * C]
                    report['pcc'] = round(float(
                        torch.corrcoef(torch.stack([a, b]))[0, 1]), 6)
                    report['max_abs_diff'] = round(float((a - b).abs().max()), 5)
                    report['arms_agree'] = report['pcc'] > 0.999
                except BaseException as error:
                    report['pcc'] = '%s: %s' % (type(error).__name__, str(error)[:200])

            if report.get('fir_ms') and report.get('shift_ms'):
                report['speedup'] = round(report['fir_ms'] / report['shift_ms'], 3)
                agree = report.get('arms_agree')
                report['reading'] = (
                    'arms DISAGREE, so the timing means nothing until the composition is fixed'
                    if agree is False else
                    'shift-by-matmul is cheaper: a kernel on this pattern is worth building'
                    if report['speedup'] > 1.2 else
                    'no material win at the ttnn level; the kernel premise needs rechecking')
        finally:
            ttnn.close_mesh_device(mesh)
    except BaseException as error:
        report['error'] = '%s: %s' % (type(error).__name__, str(error)[:300])
        report['traceback'] = traceback.format_exc()[-1800:]

    print(BEGIN, flush=True)
    print(json.dumps(report, indent=2, default=str), flush=True)
    print(END, flush=True)
    if options.json:
        io.open(options.json, 'w', encoding='utf-8', newline='\n').write(
            json.dumps(report, indent=2, default=str) + '\n')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
