"""The host KV tier's audited gate twin (docs/prefix-store-hygiene.md), generated from the production profile (stdlib only).

    python3 scripts/ci/make_prefix_tier_profiles.py --write   regenerate the twin in scripts/ci/qwen_c2_profiles.json
    python3 scripts/ci/make_prefix_tier_profiles.py --check   exit 1 if the checked-in twin is not what the parent generates

NEVER hand-merge this entry into the profiles file. After the branch is merged with another that moves the parent (the ship profile), regenerate: the twin is the
parent's env, engine and every other field byte for byte, minus the owner traffic waiver (a gate-only profile carries none), plus exactly the env below, and
gate_only.

  -tier-audit  the production stack (Lever N + prefix reuse + W2 + engine reuse) with the two prefix-store features that no card has run, every instrument on:
               the host KV tier (QWEN_PREFIX_HOST_TIER_GIB: evicted attention-KV pages go to host RAM and come back on a returning turn, byte for byte),
               the GDN checkpoints stored in the device's own tile layout and dtype (QWEN_PREFIX_CKPT_PRECONVERTED: the restore is a straight upload),
               the read-back of every restored block compared with the bytes written (QWEN_PREFIX_HOST_TIER_AUDIT), the digest of every block checked at
               restore (QWEN_PREFIX_HOST_TIER_VERIFY=all) and the preconverted tensors compared with today's conversion on card
               (QWEN_PREFIX_CKPT_PRECONVERTED_AUDIT). The tier's own kill-switch file is a scratch path inside the container (the gate writes it).
               QWEN_FAST_TP4_SDPA_AUDIT=1 rides along: the parent runs the multi-user SDPA launch (W2), which refuses the extent audit the gate gives every audited
               arm unless it carries its own audit (c2_serving_gate.multi_audit_refusal) - the SDPA slice of the combined audits, nothing else.
               The TIMED tier arm is this profile derived by c2_prefix_gate (the `tiertime` kind: the same, with the audit instruments off, the SDPA audit among them).

Gate only: the contract refuses every one of these names on a traffic profile (serving_c2_contract.prefix_policy_problems) until a qualification record lifts it.
"""

import argparse
import copy
import json
from pathlib import Path
import sys

PROFILES = Path(__file__).resolve().parent / 'qwen_c2_profiles.json'

PARENT = 'c2-packed-tp4-8x262k-ship-prefix-levern-w2-er-traffic'
TWIN = 'c2-packed-tp4-8x262k-ship-prefix-levern-w2-er-tier-audit'
# The owner's defaults (32 GiB of host RAM for the whole prefix state, swap off): the checkpoint store keeps its 8 GiB, the KV pages get the rest.
TIER_GIB = '32'
OFF_PATH = '/tmp/qwen-prefix-host-tier.off'        # prefix_replay.TIER_DRILL_OFF_PATH
ENV = {'QWEN_PREFIX_HOST_TIER_GIB': TIER_GIB, 'QWEN_PREFIX_HOST_TIER_AUDIT': '1', 'QWEN_PREFIX_HOST_TIER_VERIFY': 'all',
       'QWEN_PREFIX_CKPT_PRECONVERTED': '1', 'QWEN_PREFIX_CKPT_PRECONVERTED_AUDIT': '1', 'QWEN_PREFIX_HOST_TIER_OFF_PATH': OFF_PATH,
       'QWEN_FAST_TP4_SDPA_AUDIT': '1'}
WAIVER_FIELD = 'owner_traffic_waiver'
# Where the twin sits: right after the W2 kill drill's twin of the same parent (which sits right after the parent: test_w2_switch holds that), else after the
# parent. NOT at the end of the file: the region-read twins (make_kvread_profiles) own the end.
AFTER = 'c2-packed-tp4-8x262k-ship-prefix-levern-w2-er-kill'


def description():
    return ('GATE ONLY, UNQUALIFIED (the host KV tier and the preconverted checkpoints, docs/prefix-store-hygiene.md; never traffic, never a timed arm: the tier gate derives its '
            'timed arm). The parent is %s, the production profile (Lever N + prefix reuse + W2 + engine reuse), and this profile is that parent plus exactly %s and nothing '
            'else (QWEN_FAST_TP4_SDPA_AUDIT=1 is the multi-user SDPA launch\'s own audit, which the gate\'s extent audit needs beside W2), without its owner traffic waiver. Evicted attention-KV pages go to host RAM (%s GiB for the whole prefix state, the checkpoint store keeping its own '
            'share) and a returning turn restores them before vLLM looks for its hit; the GDN checkpoints are stored already converted to the device\'s tile layout and '
            'dtype. Every instrument is on: each restored block is read back and compared with the bytes written, each block\'s digest is checked at restore, and the '
            'preconverted tensors are compared with today\'s conversion. The tier\'s kill-switch file is %s inside the container. Needs the qwen_kv_read extension, '
            'version 2 (the raw block read and write). Generated by scripts/ci/make_prefix_tier_profiles.py: regenerate, never hand-merge.'
            % (PARENT, ', '.join('%s=%s' % pair for pair in sorted(ENV.items())), TIER_GIB, OFF_PATH))


def twin_names():
    """The generated twin's name (the profile-enumerating tests exempt it: test_prefix_tier_profiles holds it)."""
    return (TWIN,)


def parent_problems(profile):
    """Why the parent cannot be twinned, [] when it can."""
    problems = []
    env = profile.get('env') or {}
    for name in ENV:
        if name in env:
            problems.append('%s already names %s: a parent never carries the knob it is twinned with' % (PARENT, name))
    if profile.get('gate_only') is True:
        problems.append('%s is gate_only: the parent is the production traffic profile' % PARENT)
    if env.get('QWEN_FAST_TP4_SDPA') != 'multi':
        problems.append('%s does not run the multi-user SDPA launch (QWEN_FAST_TP4_SDPA=multi): the SDPA audit this twin adds would have nothing to audit' % PARENT)
    if env.get('QWEN_PREFIX_REUSE') != '1':
        problems.append('%s does not run prefix reuse (QWEN_PREFIX_REUSE=1): the tier has nothing to hold' % PARENT)
    if float(env.get('QWEN_PREFIX_STORE_GIB') or 8) >= float(TIER_GIB):
        problems.append('%s names QWEN_PREFIX_STORE_GIB=%s, not under the tier\'s %s GiB: nothing would be left for KV pages' % (
            PARENT, env.get('QWEN_PREFIX_STORE_GIB'), TIER_GIB))
    return problems


def generate(data):
    """data's profiles with the twin inserted after AFTER (every other entry unmoved: the other generators own the order of their own blocks, and the tests
    that hold it look for their twins right after a parent or at the end); returns the new dict."""
    profiles = data['profiles']
    if PARENT not in profiles:
        raise ValueError('the parent profile %s is not defined' % PARENT)
    problems = parent_problems(profiles[PARENT])
    if problems:
        raise ValueError('; '.join(problems))
    twin = copy.deepcopy(profiles[PARENT])
    twin['env'].update(ENV)
    twin['description'] = description()
    twin.pop(WAIVER_FIELD, None)
    twin.pop('gate_only', None)
    twin['gate_only'] = True
    anchor = AFTER if AFTER in profiles else PARENT
    result = {}
    for name, profile in profiles.items():
        if name == TWIN:
            continue                                    # a previous generation: replaced below
        result[name] = profile
        if name == anchor:
            result[TWIN] = twin
    out = dict(data)
    out['profiles'] = result
    return out


def render(data):
    return json.dumps(data, indent=2, ensure_ascii=False) + '\n'


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--write', action='store_true')
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--path', default=str(PROFILES))
    arguments = parser.parse_args(argv)
    path = Path(arguments.path)
    current = path.read_text(encoding='utf-8')
    wanted = render(generate(json.loads(current)))
    if arguments.check:
        if wanted != current:
            sys.stderr.write('%s is not what make_prefix_tier_profiles.py generates from its parent: run it with --write\n' % path)
            return 1
        return 0
    if arguments.write:
        if wanted != current:
            with open(str(path), 'w', encoding='utf-8', newline='\n') as handle:
                handle.write(wanted)
        return 0
    parser.error('--write or --check')


if __name__ == '__main__':
    sys.exit(main())
