"""The draft-vocabulary timing twins (docs/tp4-draft-vocab.md), generated from their parent (stdlib only).

    python3 scripts/ci/make_dvocab_profiles.py --write   regenerate the twins in scripts/ci/qwen_c2_profiles.json
    python3 scripts/ci/make_dvocab_profiles.py --check   exit 1 if the checked-in twins are not what the parent generates

NEVER hand-merge these entries into the profiles file. After the branch is merged with another that moves the parent, regenerate. They sit right before the region-read audit twins,
which make_kvread_profiles keeps at the end of the file (every other entry unmoved: the other generators own the order of their own blocks).

The parent is the engine-reuse stack at eight seats x 262k (Lever N + prefix reuse + engine reuse, two quad draft passes per eight-live round, unaudited). Its pooled KV sits at the edge of what
the cards' DRAM holds (19,968 blocks of 19,979), so the sliced head weight the shortlist uploads at the attach (about 56 MB a chip in the target head's bfloat8_b, 105 MB if it were bfloat16) has
to be given back by the pool, the way the bf16 drafter's 405 MB is (docs/tp4-drafter-bf16.md). Both twins therefore carry the same smaller pool, so the pair differs in the lever alone:

  -dvocab-control-parked   THE CONTROL OF THE ABAB: the parent with `num-gpu-blocks-override` 19,712 (256 blocks of 557,056 bytes, 142.6 MB, given back) and QWEN36_MAX_TOKENS_ALL_USERS (19,712 - 8)
                           x 64. Nothing else. No shortlist.
  -dvocab-parked           THE TIMED ARM: the control plus QWEN_FAST_DRAFT_VOCAB=coding-40960, the drafter proposing from the 40,960-row coding shortlist. The target still verifies every row
                           of the full vocabulary, so the text must equal the control's (levern_compare.py) and only the accepted length can move.

The tau lab's arm is not a profile of this file: c2_tau_lab.derive_profile adds the same flag to the production profile at run time (DRAFTER_ARMS['dvocab']).
"""

import argparse
import copy
import json
from pathlib import Path
import sys

import make_kvread_profiles

PROFILES = Path(__file__).resolve().parent / 'qwen_c2_profiles.json'

FLAG = 'QWEN_FAST_DRAFT_VOCAB'
NAME = 'coding-40960'
PARENT = 'c2-packed-tp4-8x262k-ship-prefix-levern-parked'
CONTROL = 'c2-packed-tp4-8x262k-ship-prefix-levern-dvocab-control-parked'
TWIN = 'c2-packed-tp4-8x262k-ship-prefix-levern-dvocab-parked'
SEATS = 8
PARENT_BLOCKS = 19968
BLOCKS = 19712
BLOCK_BYTES = 557056
BLOCKS_FIELD = 'num-gpu-blocks-override'
MAX_TOKENS_ENV = 'QWEN36_MAX_TOKENS_ALL_USERS'
CONTROL_ENV = {MAX_TOKENS_ENV: str((BLOCKS - SEATS) * 64)}
ENV = {FLAG: NAME}


def given_back_mb():
    return (PARENT_BLOCKS - BLOCKS) * BLOCK_BYTES / 1e6


def description(control):
    common = ('GATE ONLY, UNQUALIFIED (QWEN_FAST_DRAFT_VOCAB, docs/tp4-draft-vocab.md; never traffic). The parent is %s. Both twins carry a pool of %d blocks, not its %d (%.1f MB of DRAM a chip given back for the '
              'sliced head weight, 56 MB in bfloat8_b and 105 MB in bfloat16), and %s=%s. ' % (PARENT, BLOCKS, PARENT_BLOCKS, given_back_mb(), MAX_TOKENS_ENV, CONTROL_ENV[MAX_TOKENS_ENV]))
    if control:
        return (common + 'THE CONTROL of the timed ABAB: no shortlist, the parent\'s drafter. Generated by scripts/ci/make_dvocab_profiles.py: regenerate, never hand-merge.')
    return (common + 'THE TIMED ARM: this profile is the control (%s) plus exactly %s=%s and nothing else. The drafter\'s head runs over the sliced copy of the target head that holds the shortlist\'s rows '
            '(40,960 of 248,320, re-sharded evenly: 10,240 columns a chip) and its top-16 is one launch a chip instead of two, so each of the four head matmuls an eight-live round makes streams about a '
            'sixth of the weights and the readback is half as many reads. The target still verifies the full vocabulary: the text must equal the control\'s, and only the accepted length (tau) can '
            'move. Generated by scripts/ci/make_dvocab_profiles.py: regenerate, never hand-merge.' % (CONTROL, FLAG, NAME))


def twin_names():
    """The generated twins' names (the profile-enumerating tests exempt them through profile_twins: test_tp4_draft_vocab_jobs holds them)."""
    return (CONTROL, TWIN)


def parent_problems(profile):
    """Why the parent cannot be twinned, [] when it can."""
    problems = []
    env = profile.get('env') or {}
    for name in tuple(ENV) + tuple(CONTROL_ENV):
        if name in env and name != MAX_TOKENS_ENV:
            problems.append('%s already names %s: a parent never carries the lever it is twinned with' % (PARENT, name))
    if profile.get('gate_only') is not True:
        problems.append('%s is not gate_only: the twins are gate arms' % PARENT)
    if env.get('QWEN_FAST_TP') != '4' or profile.get('mesh_device') != 'P150x4':
        problems.append('%s is not a four-card profile: the shortlist head is a four-card lever' % PARENT)
    if env.get('QWEN_FAST_QUAD_DRAFT_BLOCKS') != '2':
        problems.append('%s does not draft an eight-live round with two quad passes (QWEN_FAST_QUAD_DRAFT_BLOCKS=2): there is no round to time' % PARENT)
    engine = profile.get('engine') or {}
    if engine.get(BLOCKS_FIELD) != PARENT_BLOCKS or engine.get('max-num-seqs') != SEATS:
        problems.append('%s does not hold %d blocks for %d seats: the pool arithmetic below is not its' % (PARENT, PARENT_BLOCKS, SEATS))
    if env.get(MAX_TOKENS_ENV) != str((PARENT_BLOCKS - SEATS) * 64):
        problems.append('%s does not carry %s=%d' % (PARENT, MAX_TOKENS_ENV, (PARENT_BLOCKS - SEATS) * 64))
    return problems


def generate(data):
    """data's profiles with the twins inserted before the region-read twins at the end of the file (every other entry unmoved); returns the new dict."""
    profiles = data['profiles']
    if PARENT not in profiles:
        raise ValueError('the parent profile %s is not defined' % PARENT)
    problems = parent_problems(profiles[PARENT])
    if problems:
        raise ValueError('; '.join(problems))
    control = copy.deepcopy(profiles[PARENT])
    control['engine'][BLOCKS_FIELD] = BLOCKS
    control['env'].update(CONTROL_ENV)
    control['description'] = description(True)
    control['gate_only'] = True
    twin = copy.deepcopy(control)
    twin['env'].update(ENV)
    twin['description'] = description(False)
    tail = set(make_kvread_profiles.twin_names())
    result = {}
    for name, profile in profiles.items():
        if name in twin_names():
            continue                                    # a previous generation: replaced below
        if name in tail and CONTROL not in result:
            result[CONTROL] = control
            result[TWIN] = twin
        result[name] = profile
    result.setdefault(CONTROL, control)
    result.setdefault(TWIN, twin)
    out = dict(data)
    out['profiles'] = result
    return out


def render(data):
    return json.dumps(data, indent=2, ensure_ascii=False) + '\n'


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--write', action='store_true')
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--path', default=str(PROFILES))
    arguments = parser.parse_args(argv)
    path = Path(arguments.path)
    current = path.read_text(encoding='utf-8')
    wanted = render(generate(json.loads(current)))
    if arguments.check:
        if wanted != current:
            sys.stderr.write('%s is not what make_dvocab_profiles.py generates from its parent: run it with --write\n' % path)
            return 1
        return 0
    if arguments.write:
        if wanted != current:
            with open(str(path), 'w', encoding='utf-8', newline='\n') as handle:
                handle.write(wanted)
        return 0
    parser.error('--write or --check')


if __name__ == '__main__':
    sys.exit(main())
