"""The adaptive Lever N governor's gate-only profile (docs/lever-n-adaptive-governor.md), generated from the production profile (stdlib only).

    python3 scripts/ci/make_adaptive_profiles.py --write   regenerate the twin in scripts/ci/qwen_c2_profiles.json
    python3 scripts/ci/make_adaptive_profiles.py --check   exit 1 if the checked-in twin is not what the parent generates

NEVER hand-merge this entry into the profiles file. After the branch is merged with another that moves the parent (the ship profile), regenerate: the twin is
the parent's env, engine and every other field byte for byte, minus the owner traffic waiver (a gate-only profile carries none), plus exactly the four adaptive
governor names below, and gate_only. The control of an ABAB is the parent itself (the production profile, which ships the policy unarmed and unnamed).

  -adaptive   the production stack with QWEN_FAST_LEVERN_ADAPTIVE=1: while one or two decoders are live the deadline governor starts from a prefill share of 0.9
              and a 120 s target instead of 0.5 and 180 s; with three or more live it paces exactly as production does. The decode-gap floor (8 s) is the parent's.
"""

import argparse
import copy
import json
from pathlib import Path
import sys

import make_kvread_profiles

PROFILES = Path(__file__).resolve().parent / 'qwen_c2_profiles.json'

PARENT = 'c2-packed-tp4-8x262k-ship-prefix-levern-w2-er-traffic'
TWIN = 'c2-packed-tp4-8x262k-ship-prefix-levern-w2-er-adaptive'
# The values are the policy's own defaults, written out so the launched argv names what ran (the rule of reading the launched environment).
ENV = {'QWEN_FAST_LEVERN_ADAPTIVE': '1', 'QWEN_FAST_LEVERN_ADAPTIVE_DECODERS': '2', 'QWEN_FAST_LEVERN_ADAPTIVE_SHARE': '0.9', 'QWEN_FAST_LEVERN_ADAPTIVE_TTFT_S': '120'}
WAIVER_FIELD = 'owner_traffic_waiver'


def description():
    return ('GATE ONLY, UNQUALIFIED (the adaptive Lever N governor, docs/lever-n-adaptive-governor.md; never traffic). The parent is %s, the production profile (Lever N + '
            'prefix reuse + W2 + engine reuse), and this profile is that parent plus exactly QWEN_FAST_LEVERN_ADAPTIVE=1, QWEN_FAST_LEVERN_ADAPTIVE_DECODERS=%s, '
            'QWEN_FAST_LEVERN_ADAPTIVE_SHARE=%s and QWEN_FAST_LEVERN_ADAPTIVE_TTFT_S=%s and nothing else, without its owner traffic waiver. While at most %s decoders are live '
            'the deadline governor starts from a prefill share of %s and a %s s target (production: 0.5 and 180 s); with more decoders live the pacing is production\'s, '
            'step for step, and the decode-gap floor (QWEN_FAST_LEVERN_MAX_DECODE_GAP_S=8) is untouched. The control of the paired timing is %s itself. Generated by '
            'scripts/ci/make_adaptive_profiles.py: regenerate, never hand-merge.'
            % (PARENT, ENV['QWEN_FAST_LEVERN_ADAPTIVE_DECODERS'], ENV['QWEN_FAST_LEVERN_ADAPTIVE_SHARE'], ENV['QWEN_FAST_LEVERN_ADAPTIVE_TTFT_S'],
               ENV['QWEN_FAST_LEVERN_ADAPTIVE_DECODERS'], ENV['QWEN_FAST_LEVERN_ADAPTIVE_SHARE'], ENV['QWEN_FAST_LEVERN_ADAPTIVE_TTFT_S'], PARENT))


def twin_names():
    """The generated twin's name (the profile-enumerating tests exempt it through profile_twins: test_adaptive_profiles holds it)."""
    return (TWIN,)


def parent_problems(profile):
    """Why the parent cannot be twinned, [] when it can."""
    problems = []
    env = profile.get('env') or {}
    for name in ENV:
        if name in env:
            problems.append('%s already names %s: a parent never carries the policy it is twinned with' % (PARENT, name))
    if profile.get('gate_only') is True:
        problems.append('%s is gate_only: the parent is the production traffic profile' % PARENT)
    if env.get('QWEN_FAST_LEVER_N') != '1' or env.get('QWEN_PREFIX_REUSE') != '1':
        problems.append('%s does not run the merged route (QWEN_FAST_LEVER_N=1, QWEN_PREFIX_REUSE=1): the deadline governor and the floor live there' % PARENT)
    if env.get('QWEN_FAST_LEVERN_ROUNDS') is not None or env.get('QWEN_FAST_LEVERN_PREFILL_SHARE', '0.5') == '1':
        problems.append('%s paces by static rounds or at share 1.0: there is no share to adapt' % PARENT)
    if env.get('QWEN_FAST_LEVERN_MAX_DECODE_GAP_S', '8') == '0':
        problems.append('%s has the decode-gap floor off: the adaptive policy requires it' % PARENT)
    return problems


def generate(data):
    """data's profiles with the twin inserted just before the region-read audit twins that close the file (every other entry unmoved: the other generators own
    the order of their own blocks, and the tests that hold it look for their twins right after a parent or at the very end); an existing twin keeps its place.
    Returns the new dict."""
    profiles = data['profiles']
    if PARENT not in profiles:
        raise ValueError('the parent profile %s is not defined' % PARENT)
    problems = parent_problems(profiles[PARENT])
    if problems:
        raise ValueError('; '.join(problems))
    twin = copy.deepcopy(profiles[PARENT])
    twin['env'].update(ENV)
    twin['description'] = description()
    twin.pop(WAIVER_FIELD, None)
    twin.pop('gate_only', None)
    twin['gate_only'] = True
    closing = set(make_kvread_profiles.twin_names())
    result = {}
    for name, profile in profiles.items():
        if name == TWIN:
            result[name] = twin                         # a previous generation: replaced in place
            continue
        if name in closing and TWIN not in result:
            result[TWIN] = twin
        result[name] = profile
    if TWIN not in result:
        result[TWIN] = twin
    out = dict(data)
    out['profiles'] = result
    return out


def render(data):
    return json.dumps(data, indent=2) + '\n'


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--write', action='store_true')
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--path', default=str(PROFILES))
    arguments = parser.parse_args(argv)
    path = Path(arguments.path)
    current = path.read_text(encoding='utf-8')
    wanted = render(generate(json.loads(current)))
    if arguments.check:
        if wanted != current:
            sys.stderr.write('%s is not what make_adaptive_profiles.py generates from its parent: run it with --write\n' % path)
            return 1
        return 0
    if arguments.write:
        if wanted != current:
            with open(str(path), 'w', encoding='utf-8', newline='\n') as handle:
                handle.write(wanted)
        return 0
    parser.error('--write or --check')


if __name__ == '__main__':
    sys.exit(main())
