"""The W2 kill-switch drill profile (docs/tp4-w2-kill-switch.md), generated from the production profile (stdlib only).

    python3 scripts/ci/make_w2_kill_profiles.py --write   regenerate the twin in scripts/ci/qwen_c2_profiles.json
    python3 scripts/ci/make_w2_kill_profiles.py --check   exit 1 if the checked-in twin is not what the parent generates

NEVER hand-merge this entry into the profiles file. After the branch is merged with another that moves the parent (the ship profile), regenerate: the twin is
the parent's env, engine and every other field byte for byte, minus the owner traffic waiver (a gate-only profile carries none), plus exactly the two W2
kill-switch names below, and gate_only. The control for the exactness read is the parent without W2: PRODUCTION_CONTROL (Lever N + prefix + engine reuse).

  -kill   the production stack with the W2 drill: after QWEN_FAST_W2_OFF_AFTER packed rounds the server writes the flag file named by QWEN_FAST_W2_OFF_PATH (a scratch
          path inside the container, never the hub mount's) and the ordinary poll latches the kill: the rounds that follow take the exact sequential step.
"""

import argparse
import copy
import json
from pathlib import Path
import sys

PROFILES = Path(__file__).resolve().parent / 'qwen_c2_profiles.json'

PARENT = 'c2-packed-tp4-8x262k-ship-prefix-levern-w2-er-traffic'
PRODUCTION_CONTROL = 'c2-packed-tp4-8x262k-ship-prefix-levern-parked'
TWIN = 'c2-packed-tp4-8x262k-ship-prefix-levern-w2-er-kill'
OFF_PATH = '/tmp/qwen-w2.off'
# Packed rounds counted over both blocks. concurrent8_steady and concurrent8_code_equal (eight users, 800 tokens each, about 5 tokens a round: about 160 steps of two block
# rounds each) run about 320 block rounds apiece, so 480 lands the kill about half way through the second of them, with the first complete on W2 and half of the second to come.
OFF_AFTER = '480'
ENV = {'QWEN_FAST_W2_OFF_PATH': OFF_PATH, 'QWEN_FAST_W2_OFF_AFTER': OFF_AFTER}
WAIVER_FIELD = 'owner_traffic_waiver'


def description():
    return ('GATE ONLY, UNQUALIFIED (the W2 kill-switch drill, docs/tp4-w2-kill-switch.md; never traffic, never a timed arm). The parent is %s, the production profile (Lever N + '
            'prefix reuse + W2 + engine reuse), and this profile is that parent plus exactly QWEN_FAST_W2_OFF_PATH=%s and QWEN_FAST_W2_OFF_AFTER=%s and nothing else, without '
            'its owner traffic waiver. After %s packed rounds (counted over both blocks) the server writes the flag file itself and the poll latches the W2 kill switch: every '
            'later round goes to the exact sequential step (the served SDPA, unspread conv gates). The control of the text comparison is %s (the same stack without W2). '
            'Generated by scripts/ci/make_w2_kill_profiles.py: regenerate, never hand-merge.' % (PARENT, OFF_PATH, OFF_AFTER, OFF_AFTER, PRODUCTION_CONTROL))


def twin_names():
    """The generated twin's name (the profile-enumerating tests exempt it: test_w2_switch holds it)."""
    return (TWIN,)


def parent_problems(profile):
    """Why the parent cannot be twinned, [] when it can."""
    problems = []
    for name in ENV:
        if name in (profile.get('env') or {}):
            problems.append('%s already names %s: a parent never carries the drill it is twinned with' % (PARENT, name))
    if profile.get('gate_only') is True:
        problems.append('%s is gate_only: the parent is the production traffic profile' % PARENT)
    env = profile.get('env') or {}
    if env.get('QWEN_FAST_TP4_SDPA') != 'multi' or env.get('QWEN_FAST_TP4_CONV_GATES_SPREAD') != '1':
        problems.append('%s does not run W2 (QWEN_FAST_TP4_SDPA=multi, QWEN_FAST_TP4_CONV_GATES_SPREAD=1): there is nothing to kill' % PARENT)
    return problems


def generate(data):
    """data's profiles with the twin inserted right after its parent (every other entry unmoved); returns the new dict."""
    profiles = data['profiles']
    if PARENT not in profiles:
        raise ValueError('the parent profile %s is not defined' % PARENT)
    if PRODUCTION_CONTROL not in profiles:
        raise ValueError('the control profile %s is not defined' % PRODUCTION_CONTROL)
    problems = parent_problems(profiles[PARENT])
    if problems:
        raise ValueError('; '.join(problems))
    twin = copy.deepcopy(profiles[PARENT])
    twin['env'].update(ENV)
    twin['description'] = description()
    twin.pop(WAIVER_FIELD, None)
    twin.pop('gate_only', None)
    twin['gate_only'] = True
    result = {}
    for name, profile in profiles.items():
        if name == TWIN:
            continue                                    # a previous generation: replaced below
        result[name] = profile
        if name == PARENT:
            result[TWIN] = twin
    out = dict(data)
    out['profiles'] = result
    return out


def render(data):
    return json.dumps(data, indent=2) + '\n'


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--write', action='store_true')
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--path', default=str(PROFILES))
    arguments = parser.parse_args(argv)
    path = Path(arguments.path)
    current = path.read_text(encoding='utf-8')
    wanted = render(generate(json.loads(current)))
    if arguments.check:
        if wanted != current:
            sys.stderr.write('%s is not what make_w2_kill_profiles.py generates from its parent: run it with --write\n' % path)
            return 1
        return 0
    if arguments.write:
        if wanted != current:
            with open(str(path), 'w', encoding='utf-8', newline='\n') as handle:
                handle.write(wanted)
        return 0
    parser.error('--write or --check')


if __name__ == '__main__':
    sys.exit(main())
