"""The op-fusion programme's integration scaffolding (docs/tp4-fusion.md), generated from the work packages' manifests (stdlib only).

    python3 scripts/ci/make_fusion_profiles.py --write    regenerate every generated block from scripts/ci/fusion-wp/*.json
    python3 scripts/ci/make_fusion_profiles.py --check    exit 1 if a checked-in block is not what the manifests generate
    python3 scripts/ci/make_fusion_profiles.py --report   one line per manifest entry and where it landed (or why it already was there)

Each work package (WP1 S1 argmax, WP2 K/V writer, WP5 CCL options, WP6 drafter reduce and MLP branch, WP7 drafter attention and permutes) owns its own
modules and writes ONE manifest, scripts/ci/fusion-wp/<WP>.json (the schema is in scripts/ci/fusion-wp/SCHEMA.md). It never edits the five shared files below;
this generator does, inside blocks fenced by `fusion-wp begin` / `fusion-wp end` comment lines, which nothing else edits (NEVER hand-merge a fenced block: after
a merge, regenerate):

  scripts/ci/qwen_c2_profiles.json         per lever, two GATE-ONLY twins of the production profile (PARENT below, byte for byte but for the owner traffic waiver
                                           and gate_only): -fx-<id> (the flag on: the timed arm) and -fx-<id>-audit (plus the lever's _AUDIT flag: the exactness arm)
  scripts/ci/c2_smoke_check.py             FUSION_LEVERS / FUSION_AUDITS, the marker tables fusion_problems() reads (a fall-back line fails the smoke; a profile that
                                           asks for the lever and logs no engaged line fails; an audit flag with no 'exact=True' audit line fails), and FUSION_RULES,
                                           the packages' own stricter rules (host-side modules with problems(env, container_text)) that it calls once per arm
  docker/qwen-c2-overlay.txt               the image copy list: the ONE list (c2_overlay.py); the P8 copy lists are not touched
  .github/workflows/qwen-integration-cpu.yml   the CPU allowlist: the regression step the any-ref CPU suite runs
  scripts/ci/tp_addresses.py               twin rows, when a package binds a twin module or class through tp_addresses

The generator is deterministic (manifests in file-name order, entries in file order, no clock, no host state), idempotent, and refuses what it cannot place:
an unknown key, a file the manifest names that the tree lacks, a flag already in the parent, two packages naming one flag or one id, an overlay line c2_overlay's
parser refuses. With no manifest every block is empty and the five files are what they were before the programme.
"""

import argparse
import copy
import json
from pathlib import Path
import re
import sys

import make_kvread_profiles

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
MANIFESTS = HERE / 'fusion-wp'
PROFILES = HERE / 'qwen_c2_profiles.json'
SMOKE = HERE / 'c2_smoke_check.py'
ADDRESSES = HERE / 'tp_addresses.py'
OVERLAY = REPO / 'docker' / 'qwen-c2-overlay.txt'
CPU_WORKFLOW = REPO / '.github' / 'workflows' / 'qwen-integration-cpu.yml'

PARENT = 'c2-packed-tp4-8x262k-ship-prefix-levern-w2-er-traffic'
BASE = 'c2-packed-tp4-8x262k-ship-prefix-levern-w2-er'
NAMESPACE = BASE + '-fx-'
WAIVER_FIELD = 'owner_traffic_waiver'
BEGIN = 'fusion-wp begin: generated by scripts/ci/make_fusion_profiles.py from scripts/ci/fusion-wp/*.json; do not edit by hand'
END = 'fusion-wp end'
SUITE_STEP = 'T32 and unchanged T16 regression gates'
IMAGE_ROOTS = ('scripts/ci/', 'speculative-decoding/harness/')

# What a manifest may hold. Aliases are the spellings a package is likely to use; they mean the canonical key.
INFO_KEYS = ('wp', 'branch', 'head', 'description', 'reason', 'notes', 'card_jobs', 'docs', 'owner', 'ci_run', 'status')
KEYS = ('levers', 'profiles', 'smoke', 'smoke_rules', 'pack_arms', 'pack_order', 'pack_last', 'image_files', 'tests', 'tp_addresses')
ALIASES = {
    'twin_profiles': 'profiles', 'profile_twins': 'profiles', 'twins': 'profiles',
    'smoke_dispatch': 'smoke', 'smoke_markers': 'smoke', 'smoke_modules': 'smoke', 'smoke_check': 'smoke',
    'image': 'image_files', 'image_copy': 'image_files', 'image_copy_entries': 'image_files', 'copy_lists': 'image_files', 'overlay': 'image_files',
    'overlay_manifest': 'image_files', 'image_entries': 'image_files',
    'cpu_tests': 'tests', 'cpu_allowlist': 'tests', 'allowlist': 'tests', 'test_modules': 'tests', 'tests_to_allowlist': 'tests',
    'tp_addresses_rows': 'tp_addresses',
    'smoke_rule': 'smoke_rules', 'smoke_check_rules': 'smoke_rules', 'pack_arm': 'pack_arms', 'card_pack': 'pack_arms',
    'pack_after': 'pack_last',
}
TP_KEYS = ('twins', 'module_twins', 'flagged_twins', 'flagged_module_twins')

FLAG = re.compile(r'^[A-Z][A-Z0-9_]*$')
ID = re.compile(r'^[a-z][a-z0-9]*(-[a-z0-9]+)*$')
MODULE = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')
TEST_MODULE = re.compile(r'^test_[A-Za-z0-9_]+(\.[A-Za-z0-9_]+)*$')
MARKER = re.compile(r'^\[PINDIAG\] [ -~]+$')


class ManifestError(ValueError):
    """A manifest (or a block target) the generator cannot place; the message names the file."""


# ---- reading and normalising the manifests ----

def read_manifests(directory=MANIFESTS):
    """[(file name, raw dict)] in file-name order; a file that is not a JSON object is refused."""
    found = []
    for path in sorted(Path(directory).glob('*.json')):
        try:
            raw = json.loads(path.read_text(encoding='utf-8'))
        except ValueError as error:
            raise ManifestError('%s: not JSON (%s)' % (path.name, error))
        if not isinstance(raw, dict):
            raise ManifestError('%s: the manifest is one JSON object' % path.name)
        found.append((path.name, raw))
    return found


def text_of(value, where, what):
    if not isinstance(value, str) or not value.strip():
        raise ManifestError('%s: %s must be a non-empty string, not %r' % (where, what, value))
    return value.strip()


def env_of(value, where, what):
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise ManifestError('%s: %s must be an object of NAME: "value"' % (where, what))
    out = {}
    for name, item in value.items():
        if not FLAG.match(name):
            raise ManifestError('%s: %s names %r, which is not an environment variable name' % (where, what, name))
        if isinstance(item, bool) or not isinstance(item, (str, int)):
            raise ManifestError('%s: %s %s must be a string or an integer, not %r' % (where, what, name, item))
        out[name] = str(item)
    return out


def listing(value, where, what, mapping=False):
    """`value` as a list. With `mapping`, an object {name: reason} is a list of {name, reason} objects (image_files and tests only)."""
    if value is None:
        return []
    if isinstance(value, dict):
        if not mapping:
            raise ManifestError('%s: %s must be a list' % (where, what))
        return [{'path': name, 'reason': reason} if isinstance(reason, str) else {'path': name} for name, reason in value.items()]
    if isinstance(value, str):
        return [value]
    if not isinstance(value, list):
        raise ManifestError('%s: %s must be a list' % (where, what))
    return value


def one_marker(value, where, what):
    marker = text_of(value, where, what)
    if not MARKER.match(marker):
        raise ManifestError('%s: %s %r must be a [PINDIAG] marker line prefix (printable ASCII)' % (where, what, marker))
    return marker


def marker_of(entry, where):
    """The engaged / fell back / audit marker prefixes of one lever: named, or '[PINDIAG] ' + marker + ' engaged|fell back|audit'."""
    base = entry.get('marker')
    markers = entry.get('markers') or {}
    if base is not None:
        base = text_of(base, where, 'marker')
        base = base if base.startswith('[PINDIAG] ') else '[PINDIAG] ' + base
        one_marker(base, where, 'marker')
    out = {}
    for key, suffix in (('engaged', ' engaged'), ('fell_back', ' fell back'), ('audit', ' audit')):
        named = markers.get(key, entry.get(key))
        if named is not None:
            out[key] = one_marker(named, where, 'marker ' + key)
        elif base is not None:
            out[key] = base + suffix
    return out


def lever_of(wp, raw, where):
    """One normalised lever: its id, flag(s), env additions and markers."""
    if not isinstance(raw, dict):
        raise ManifestError('%s: a lever is an object' % where)
    unknown = sorted(set(raw) - {'id', 'name', 'flag', 'value', 'audit_flag', 'env', 'audit_env', 'marker', 'markers', 'engaged', 'fell_back', 'audit',
                                 'reason', 'module', 'parent'})
    if unknown:
        raise ManifestError('%s: a lever has no key %s' % (where, ', '.join(unknown)))
    ident = text_of(raw.get('id'), where, 'a lever id')
    if not ID.match(ident):
        raise ManifestError('%s: lever id %r must be lower-case letters, digits and single dashes' % (where, ident))
    where = '%s (lever %s)' % (where, ident)
    flag = text_of(raw.get('flag'), where, 'flag')
    if not FLAG.match(flag):
        raise ManifestError('%s: flag %r is not an environment variable name' % (where, flag))
    audit_flag = raw.get('audit_flag')
    if audit_flag is not None:
        audit_flag = text_of(audit_flag, where, 'audit_flag')
        if not FLAG.match(audit_flag):
            raise ManifestError('%s: audit_flag %r is not an environment variable name' % (where, audit_flag))
    markers = marker_of(raw, where)
    if 'engaged' not in markers:
        raise ManifestError('%s: name the engaged marker (marker: "tp4 <lever>" gives [PINDIAG] tp4 <lever> engaged)' % where)
    if audit_flag is not None and 'audit' not in markers:
        raise ManifestError('%s: an audit flag needs an audit marker (marker: "tp4 <lever>" gives [PINDIAG] tp4 <lever> audit)' % where)
    value = raw.get('value', '1')
    if isinstance(value, bool) or not isinstance(value, (str, int)) or str(value) == '':
        raise ManifestError('%s: value must be a string or an integer' % where)
    parent = raw.get('parent')
    return dict(wp=wp, id=ident, name=text_of(raw.get('name', ident), where, 'name'), flag=flag, value=str(value), audit_flag=audit_flag,
                env=env_of(raw.get('env'), where, 'env'), audit_env=env_of(raw.get('audit_env'), where, 'audit_env'),
                fell_back=markers.get('fell_back'), engaged=markers['engaged'], audit=markers.get('audit'),
                reason=text_of(raw.get('reason', raw.get('name', ident)), where, 'reason'),
                parent=text_of(parent, where, 'parent') if parent is not None else PARENT, module=raw.get('module'))


def profile_of(wp, raw, where):
    if not isinstance(raw, dict):
        raise ManifestError('%s: a profile entry is an object' % where)
    unknown = sorted(set(raw) - {'name', 'suffix', 'env', 'parent', 'reason', 'audit', 'lever', 'flags'})
    if unknown:
        raise ManifestError('%s: a profile entry has no key %s' % (where, ', '.join(unknown)))
    name = text_of(raw.get('name', raw.get('suffix')), where, 'name')
    if not name.startswith(NAMESPACE):
        name = NAMESPACE + name
    if not ID.match(name[len(NAMESPACE):]):
        raise ManifestError('%s: profile name %r must end in lower-case letters, digits and single dashes after %s' % (where, name, NAMESPACE))
    env = env_of(raw.get('env', raw.get('flags')), where, 'env')
    if not env:
        raise ManifestError('%s: profile %s names no env: a twin is the parent plus something' % (where, name))
    return dict(wp=wp, name=name, env=env, parent=text_of(raw.get('parent', PARENT), where, 'parent'),
                reason=text_of(raw.get('reason', raw.get('lever', name)), where, 'reason'), audit=bool(raw.get('audit')))


def markers_from_list(lines, where):
    """The engaged / fell back / audit marker prefixes out of a list of marker lines (each names its kind by the word it carries)."""
    out = {}
    for line in lines:
        line = one_marker(line, where, 'a marker')
        for key, word in (('fell_back', ' fell back'), ('engaged', ' engaged'), ('audit', ' audit')):
            if word in line:
                out[key] = line[:line.index(word) + len(word)]
                break
        else:
            raise ManifestError('%s: the marker %r is none of engaged, fell back or audit' % (where, line))
    return out


def smoke_of(wp, raw, where):
    """One smoke entry; `module` (the package's smoke module, a file the image needs) is returned too so it can be listed for the overlay."""
    if not isinstance(raw, dict):
        raise ManifestError('%s: a smoke entry is an object' % where)
    unknown = sorted(set(raw) - {'flag', 'value', 'audit_flag', 'marker', 'markers', 'engaged', 'fell_back', 'audit', 'module', 'what', 'name', 'reason',
                                 'test', 'tests'})
    if unknown:
        raise ManifestError('%s: a smoke entry has no key %s' % (where, ', '.join(unknown)))
    if raw.get('flag') is None:
        raise ManifestError('%s: a smoke entry names its flag (the env flag whose presence in a profile makes the marker required)' % where)
    flag = text_of(raw.get('flag'), where, 'flag')
    if not FLAG.match(flag):
        raise ManifestError('%s: flag %r is not an environment variable name' % (where, flag))
    if isinstance(raw.get('markers'), list):
        markers = markers_from_list(raw['markers'], where)
        raw = dict(raw, markers=None)
        raw.pop('markers')
    else:
        markers = {}
    markers = dict(marker_of(raw, where), **markers)
    if 'engaged' not in markers:
        raise ManifestError('%s: smoke entry %s names no engaged marker' % (where, flag))
    audit_flag = raw.get('audit_flag')
    if audit_flag is not None:
        audit_flag = text_of(audit_flag, where, 'audit_flag')
        if 'audit' not in markers:
            raise ManifestError('%s: smoke entry %s has an audit flag and no audit marker' % (where, flag))
    value = raw.get('value', '1')
    module = raw.get('module')
    if module is not None:
        module = text_of(module, where, 'module')
        module = module if '/' in module else 'scripts/ci/' + module
    return dict(wp=wp, flag=flag, value=str(value), audit_flag=audit_flag, engaged=markers['engaged'], fell_back=markers.get('fell_back'),
                audit=markers.get('audit'), what=text_of(raw.get('what', raw.get('name', flag)), where, 'what'), module=module)


def path_entries(wp, value, where, what):
    """[(path, reason)] from strings or objects with path/file/source and reason."""
    out = []
    for item in listing(value, where, what, mapping=True):
        if isinstance(item, str):
            out.append((text_of(item, where, what), 'named by %s' % wp))
        elif isinstance(item, dict):
            unknown = sorted(set(item) - {'path', 'file', 'source', 'reason', 'why', 'name'})
            if unknown:
                raise ManifestError('%s: a %s entry has no key %s' % (where, what, ', '.join(unknown)))
            path = item.get('path', item.get('file', item.get('source', item.get('name'))))
            out.append((text_of(path, where, what), text_of(item.get('reason', item.get('why', 'named by %s' % wp)), where, 'reason')))
        else:
            raise ManifestError('%s: a %s entry is a path or an object' % (where, what))
    return out


def tests_of(wp, value, where):
    """[(module or ('discover', dir, pattern), reason)]."""
    out = []
    for item in listing(value, where, 'tests', mapping=True):
        reason = 'named by %s' % wp
        if isinstance(item, dict):
            unknown = sorted(set(item) - {'module', 'name', 'path', 'discover', 'pattern', 'reason', 'why'})
            if unknown:
                raise ManifestError('%s: a tests entry has no key %s' % (where, ', '.join(unknown)))
            reason = text_of(item.get('reason', item.get('why', reason)), where, 'reason')
            if 'discover' in item:
                directory = text_of(item['discover'], where, 'discover')
                pattern = text_of(item.get('pattern', 'test_*.py'), where, 'pattern')
                if directory.startswith('/') or '..' in directory.split('/') or not re.match(r'^[A-Za-z0-9_./-]+$', directory) or not re.match(r'^[A-Za-z0-9_*.?-]+$', pattern):
                    raise ManifestError('%s: discover %r %r is not a plain repo-relative directory and pattern' % (where, directory, pattern))
                out.append((('discover', directory.rstrip('/'), pattern), reason))
                continue
            item = item.get('module', item.get('name', item.get('path')))
        module = text_of(item, where, 'a test module')
        if module.endswith('.py'):
            module = module[:-3]
        if module.startswith('scripts/ci/'):
            module = module[len('scripts/ci/'):][:-3] if module.endswith('.py') else module[len('scripts/ci/'):]
        if not TEST_MODULE.match(module):
            raise ManifestError('%s: %r is not a test module name (test_<name>, optionally .Class.method)' % (where, module))
        out.append((module, reason))
    return out


def tp_of(wp, value, where):
    if value is None:
        return {key: [] for key in TP_KEYS}
    if not isinstance(value, dict):
        raise ManifestError('%s: tp_addresses is an object of %s' % (where, ', '.join(TP_KEYS)))
    unknown = sorted(set(value) - set(TP_KEYS) - {'reason'})
    if unknown:
        raise ManifestError('%s: tp_addresses has no key %s' % (where, ', '.join(unknown)))
    out = {key: [] for key in TP_KEYS}
    reason = value.get('reason', 'named by %s' % wp)

    def names(row, count, what):
        if not isinstance(row, list) or len(row) != count or not all(isinstance(x, str) and MODULE.match(x) for x in row):
            raise ManifestError('%s: a tp_addresses %s row is %d module or attribute names' % (where, what, count))
        return tuple(row)

    for row in listing(value.get('twins'), where, 'tp_addresses twins'):
        out['twins'].append((wp, names(row, 4, 'twins'), reason))
    for row in listing(value.get('module_twins'), where, 'tp_addresses module_twins'):
        out['module_twins'].append((wp, names(row, 2, 'module_twins'), reason))
    for key, count in (('flagged_twins', 2), ('flagged_module_twins', 1)):
        for row in listing(value.get(key), where, 'tp_addresses ' + key):
            if not isinstance(row, dict) or set(row) - {'module', 'attr', 'flag', 'gate'}:
                raise ManifestError('%s: a tp_addresses %s row is an object of module%s, flag, gate' % (where, key, ', attr' if count == 2 else ''))
            gate = text_of(row.get('gate'), where, 'gate')
            if not re.match(r'^[A-Za-z_][A-Za-z0-9_]*:[A-Za-z_][A-Za-z0-9_]*$', gate):
                raise ManifestError('%s: gate %r is module:function (the function takes the environment mapping and returns a bool)' % (where, gate))
            key_names = [text_of(row.get('module'), where, 'module')] + ([text_of(row.get('attr'), where, 'attr')] if count == 2 else [])
            if not all(MODULE.match(x) for x in key_names):
                raise ManifestError('%s: %s names %r, which is not a module or attribute name' % (where, key, key_names))
            out[key].append((wp, dict(key=tuple(key_names), flag=text_of(row.get('flag'), where, 'flag'), gate=gate), reason))
    return out


def normalise(manifests):
    """The plan: every manifest's entries in one structure, in file-name then file order. Names collide across packages: refused."""
    plan = dict(levers=[], profiles=[], smoke=[], smoke_rules=[], pack_arms=[], pack_order=[], pack_last=[], image_files=[], tests=[], tp={key: [] for key in TP_KEYS}, info=[])
    for file_name, raw in manifests:
        where = 'fusion-wp/' + file_name
        wp = text_of(raw.get('wp', Path(file_name).stem.upper()), where, 'wp')
        canonical = {}
        for key, value in raw.items():
            if key in INFO_KEYS:
                continue
            target = ALIASES.get(key, key)
            if target not in KEYS:
                raise ManifestError('%s: the key %r is not one the integrator places (%s); put it under one of those or under notes' % (
                    where, key, ', '.join(KEYS)))
            if target in canonical:
                raise ManifestError('%s: %r and %r are both %s' % (where, key, canonical[target][0], target))
            canonical[target] = (key, value)
        plan['info'].append(dict(wp=wp, file=file_name, notes=raw.get('notes'), branch=raw.get('branch'), card_jobs=raw.get('card_jobs')))
        for item in listing(canonical.get('levers', (0, None))[1], where, 'levers'):
            lever = dict(lever_of(wp, item, where), file=file_name)
            plan['levers'].append(lever)
            if lever['module']:
                module = text_of(lever['module'], where, 'module')
                plan['image_files'].append((wp, module if '/' in module else 'scripts/ci/' + module, 'the smoke module of lever %s' % lever['id']))
        for item in listing(canonical.get('profiles', (0, None))[1], where, 'profiles'):
            plan['profiles'].append(dict(profile_of(wp, item, where), file=file_name))
        smoke = canonical.get('smoke', (0, None))[1]
        for item in ([smoke] if isinstance(smoke, dict) else listing(smoke, where, 'smoke')):
            entry = smoke_of(wp, item, where)
            plan['smoke'].append(entry)
            if entry['module']:
                plan['image_files'].append((wp, entry['module'], 'the smoke module of %s' % entry['flag']))
        for arm in listing(canonical.get('pack_arms', (0, None))[1], where, 'pack_arms'):
            arm = text_of(arm, where, 'a pack arm')
            arm = arm[len(NAMESPACE):] if arm.startswith(NAMESPACE) else arm
            if not ID.match(arm):
                raise ManifestError('%s: pack arm %r is the suffix of an extra profile twin (lower-case letters, digits and single dashes)' % (where, arm))
            plan['pack_arms'].append((wp, arm))
        for arm in listing(canonical.get('pack_order', (0, None))[1], where, 'pack_order'):
            arm = text_of(arm, where, 'a pack_order arm')
            arm = arm[len(NAMESPACE):] if arm.startswith(NAMESPACE) else arm
            if not ID.match(arm):
                raise ManifestError('%s: pack_order arm %r is a lever id or an extra twin suffix' % (where, arm))
            plan['pack_order'].append((wp, arm))
        for arm in listing(canonical.get('pack_last', (0, None))[1], where, 'pack_last'):
            reason = 'listed under pack_last by %s' % wp
            if isinstance(arm, dict):
                if set(arm) - {'arm', 'reason'}:
                    raise ManifestError('%s: a pack_last entry is an arm id or {"arm", "reason"}' % where)
                reason = text_of(arm.get('reason', reason), where, 'reason')
                arm = arm.get('arm')
            arm = text_of(arm, where, 'a pack_last arm')
            arm = arm[len(NAMESPACE):] if arm.startswith(NAMESPACE) else arm
            if not ID.match(arm):
                raise ManifestError('%s: pack_last arm %r is a lever id or an extra twin suffix' % (where, arm))
            plan['pack_last'].append((wp, arm, reason))
        for module in listing(canonical.get('smoke_rules', (0, None))[1], where, 'smoke_rules'):
            module = text_of(module, where, 'a smoke rule module')
            module = module[len('scripts/ci/'):] if module.startswith('scripts/ci/') else module
            module = module[:-3] if module.endswith('.py') else module
            if not MODULE.match(module):
                raise ManifestError('%s: smoke rule %r is a module in scripts/ci (its problems(env, container_text) returns a list of strings)' % (where, module))
            plan['smoke_rules'].append((wp, module))
        for path, reason in path_entries(wp, canonical.get('image_files', (0, None))[1], where, 'image_files'):
            plan['image_files'].append((wp, path, reason))
        for module, reason in tests_of(wp, canonical.get('tests', (0, None))[1], where):
            plan['tests'].append((wp, module, reason))
        for key, rows in tp_of(wp, canonical.get('tp_addresses', (0, None))[1], where).items():
            plan['tp'][key].extend(rows)
    seen = {}
    for lever in plan['levers']:
        for key, what in (('id', 'id'), ('flag', 'flag')):
            other = seen.get((what, lever[key]))
            if other:
                raise ManifestError('%s and %s both name the lever %s %s: one package owns a lever' % (other, lever['wp'], what, lever[key]))
            seen[(what, lever[key])] = lever['wp']
    explicit = set(item['name'][len(NAMESPACE):] for item in plan['profiles'])
    for wp, arm in plan['pack_arms']:
        base = arm[:-len('-audit')] if arm.endswith('-audit') else arm
        if base not in explicit and arm not in explicit:
            raise ManifestError('%s: pack arm %s is not an extra profile twin of any manifest (a lever is in the pack already)' % (wp, arm))
    known = set(lever['id'] for lever in plan['levers']) | set(arm for _wp, arm in plan['pack_arms'])
    for wp, arm, _reason in plan['pack_last']:
        if arm not in known:
            raise ManifestError('%s: pack_last arm %s is neither a lever nor a pack arm' % (wp, arm))
    listed = [arm for _wp, arm in plan['pack_order']]
    for wp, arm in plan['pack_order']:
        if arm not in known:
            raise ManifestError('%s: pack_order arm %s is neither a lever nor a pack arm' % (wp, arm))
        if listed.count(arm) > 1:
            raise ManifestError('%s: pack_order names %s twice' % (wp, arm))
    owners = {}
    for twin in profile_twins(plan):
        if twin['name'] in owners:
            raise ManifestError('%s and %s both generate the profile %s: one package owns a profile name' % (owners[twin['name']], twin['wp'], twin['name']))
        owners[twin['name']] = twin['wp']
    return plan


def sentence(text):
    """`text` on one line, ending in a full stop."""
    text = ' '.join(text.split())
    return text if text.endswith(('.', '!', '?')) else text + '.'


def twin_id(lever, audited):
    return NAMESPACE + lever['id'] + ('-audit' if audited else '')


def profile_twins(plan):
    """[dict(name, parent, env, why, wp, kind)] in the order they are written: per lever its timed and its audit twin, then the explicit profiles."""
    out = []
    for lever in plan['levers']:
        env = dict(lever['env'])
        env[lever['flag']] = lever['value']
        out.append(dict(name=twin_id(lever, False), parent=lever['parent'], env=env, wp=lever['wp'], file=lever['file'], kind='timed', lever=lever,
                        why='THIS ARM, %s (%s): %s' % (lever['name'], lever['wp'], sentence(lever['reason']))))
        if lever['audit_flag']:
            audit_env = dict(env)
            audit_env[lever['audit_flag']] = '1'
            audit_env.update(lever['audit_env'])
            out.append(dict(name=twin_id(lever, True), parent=lever['parent'], env=audit_env, wp=lever['wp'], file=lever['file'], kind='audit', lever=lever,
                            why='THIS ARM, %s audited (%s): the lever plus %s=1, which runs the served composition beside the lever on the device and logs '
                                'exact=True or a mismatch. The exactness job; not a timing arm. %s' % (lever['name'], lever['wp'], lever['audit_flag'],
                                                                                                     sentence(lever['reason']))))
    for item in plan['profiles']:
        out.append(dict(name=item['name'], parent=item['parent'], env=dict(item['env']), wp=item['wp'], file=item['file'],
                        kind='audit' if item['audit'] else 'timed', lever=None, why='THIS ARM (%s): %s' % (item['wp'], sentence(item['reason']))))
    return out


def twin_names(directory=MANIFESTS):
    """The generated twins' names (profile_twins.py exempts them from the profile-enumerating tests; test_fusion_wp holds each)."""
    return tuple(twin['name'] for twin in profile_twins(normalise(read_manifests(directory))))


# ---- the profiles file ----

def description(twin):
    env = ', '.join('%s=%s' % pair for pair in sorted(twin['env'].items()))
    return ('GATE ONLY, UNQUALIFIED (the op-fusion programme, docs/tp4-fusion.md, scripts/ci/fusion-wp/%s; never traffic). The parent is %s%s and this profile is '
            'that parent plus exactly %s and nothing else, without its owner traffic waiver. %s The lever is default off and byte-identical off; the control of the '
            'paired timing is %s itself. Generated by scripts/ci/make_fusion_profiles.py: regenerate, never hand-merge.'
            % (twin['file'], twin['parent'], ', the production profile (Lever N + prefix reuse + W2 + engine reuse)' if twin['parent'] == PARENT else '', env,
               twin['why'], PARENT))


def parent_problems(name, profile, twin):
    problems = []
    env = profile.get('env') or {}
    lever = twin['lever']
    if lever is not None:
        for flag in (lever['flag'], lever['audit_flag']):
            if flag and flag in env:
                problems.append('%s already names %s: a parent never carries the lever it is twinned with' % (name, flag))
    if profile.get('gate_only') is True and name == PARENT:
        problems.append('%s is gate_only: the parent is the production traffic profile' % PARENT)
    if profile.get('gate_only') is not True and name != PARENT:
        problems.append('%s is neither the production profile nor a gate-only profile' % name)
    return problems


def generate_profiles(data, plan):
    """data's profiles with the twins inserted just before the region-read audit twins that close the file (every other entry unmoved: the other generators own
    the order of their own blocks); a previous generation (any name under NAMESPACE) is dropped, so the namespace is exactly the manifests'. Returns the new dict."""
    profiles = data['profiles']
    twins = profile_twins(plan)
    generated = {}
    for twin in twins:
        parent = twin['parent']
        source = generated.get(parent) or profiles.get(parent)
        if source is None:
            raise ManifestError('%s: the parent profile %s is not defined' % (twin['wp'], parent))
        problems = parent_problems(parent, source, twin)
        if problems:
            raise ManifestError('%s: %s' % (twin['wp'], '; '.join(problems)))
        profile = copy.deepcopy(source)
        profile['env'].update(twin['env'])
        profile['description'] = description(twin)
        profile.pop(WAIVER_FIELD, None)
        profile.pop('gate_only', None)
        profile['gate_only'] = True
        generated[twin['name']] = profile
    closing = set(make_kvread_profiles.twin_names())
    result = {}
    for name, profile in profiles.items():
        if name.startswith(NAMESPACE):
            continue                                    # a previous generation: replaced below
        if name in closing and generated:
            result.update(generated)
            generated = {}
        result[name] = profile
    result.update(generated)
    out = dict(data)
    out['profiles'] = result
    return out


def render_profiles(data):
    return json.dumps(data, indent=2) + '\n'


# ---- fenced blocks in the other files ----

def replace_block(text, body, where):
    """`text` with the lines between the one begin and the one end marker replaced by `body` (indented as the markers are)."""
    lines = text.split('\n')
    begins = [i for i, line in enumerate(lines) if line.strip().startswith('#') and BEGIN in line]
    ends = [i for i, line in enumerate(lines) if line.strip().startswith('#') and line.strip().lstrip('#').strip() == END]
    if len(begins) != 1 or len(ends) != 1 or ends[0] < begins[0]:
        raise ManifestError('%s: needs exactly one "# %s" line followed by one "# %s" line (%d and %d found)' % (where, BEGIN, END, len(begins), len(ends)))
    indent = lines[begins[0]][:len(lines[begins[0]]) - len(lines[begins[0]].lstrip())]
    block = [(indent + line) if line else '' for line in body]
    return '\n'.join(lines[:begins[0] + 1] + block + lines[ends[0]:])


def outside(text):
    """`text` without its fenced blocks (what a manifest entry may already be named in)."""
    kept, fenced = [], False
    for line in text.split('\n'):
        stripped = line.strip()
        if stripped.startswith('#') and BEGIN in line:
            fenced = True
        elif fenced and stripped.startswith('#') and stripped.lstrip('#').strip() == END:
            fenced = False
        elif not fenced:
            kept.append(line)
    return '\n'.join(kept)


def smoke_rows(plan, text):
    """([(wp, source, lever row)], [(wp, source, audit row)], report) for the smoke tables; a flag the static tables already dispatch is not repeated."""
    static = outside(text)
    taken = {}
    for flag, marker in re.findall(r"\('(QWEN_[A-Z0-9_]+)', '(\[PINDIAG\][^']*)'", static):
        taken.setdefault(flag, []).append(marker)
    entries = []
    for lever in plan['levers']:
        entries.append(dict(wp=lever['wp'], flag=lever['flag'], value=lever['value'], audit_flag=lever['audit_flag'], engaged=lever['engaged'],
                            fell_back=lever['fell_back'], audit=lever['audit'], what=lever['name'], origin='lever ' + lever['id']))
    for item in plan['smoke']:
        entries.append(dict(item, origin='smoke ' + item['flag']))
    levers, audits, report, seen = [], [], [], set()
    for entry in entries:
        flag = entry['flag']
        if flag in taken and any(entry['engaged'].startswith(m) or m.startswith(entry['engaged']) for m in taken[flag]):
            report.append((entry['wp'], entry['origin'], 'c2_smoke_check.py', 'existing', 'the static tables already dispatch %s' % flag))
        elif flag in taken:
            raise ManifestError('%s: %s is already dispatched by c2_smoke_check.py with the markers %s, not %s' % (
                entry['wp'], flag, ' / '.join(taken[flag]), entry['engaged']))
        elif (flag, entry['value']) in seen:
            report.append((entry['wp'], entry['origin'], 'c2_smoke_check.py', 'existing', '%s=%s is dispatched once for the lever and its smoke entry' % (flag, entry['value'])))
        else:
            seen.add((flag, entry['value']))
            levers.append((entry['wp'], entry['origin'], (flag, entry['value'], entry['engaged'], entry['fell_back'] or (entry['engaged'].rsplit(' ', 1)[0] + ' fell back'),
                                                         entry['what'])))
            report.append((entry['wp'], entry['origin'], 'c2_smoke_check.py', 'landed', 'FUSION_LEVERS %s' % flag))
        audit_flag = entry['audit_flag']
        if audit_flag:
            if audit_flag in taken:
                report.append((entry['wp'], entry['origin'], 'c2_smoke_check.py', 'existing', 'the static tables already dispatch %s' % audit_flag))
            elif ('audit', audit_flag) in seen:
                report.append((entry['wp'], entry['origin'], 'c2_smoke_check.py', 'existing', '%s is dispatched once' % audit_flag))
            else:
                seen.add(('audit', audit_flag))
                audits.append((entry['wp'], entry['origin'], (audit_flag, entry['audit'], entry['what'])))
                report.append((entry['wp'], entry['origin'], 'c2_smoke_check.py', 'landed', 'FUSION_AUDITS %s' % audit_flag))
    return levers, audits, report


def smoke_block(levers, audits, rules=()):
    lines = ['FUSION_LEVERS = (']
    lines += ['    %s,  # %s' % (repr(row), wp) for wp, _origin, row in levers]
    lines += [')', 'FUSION_AUDITS = (']
    lines += ['    %s,  # %s' % (repr(row), wp) for wp, _origin, row in audits]
    lines += [')', 'FUSION_RULES = (']
    lines += ['    %s,  # %s' % (repr(module), wp) for wp, module in rules]
    lines += [')']
    return lines


def rule_rows(plan, root):
    """([(wp, module)], report): the packages' own smoke rules (a host-side module in scripts/ci with problems(env, container_text)), each once."""
    rows, report, seen = [], [], set()
    for wp, module in plan['smoke_rules']:
        path = Path(root) / 'scripts' / 'ci' / (module + '.py')
        if not path.is_file():
            raise ManifestError('%s: smoke rule module %s is not in scripts/ci' % (wp, module))
        if 'def problems(' not in path.read_text(encoding='utf-8'):
            raise ManifestError('%s: smoke rule module %s has no problems(env, container_text)' % (wp, module))
        if module in seen:
            report.append((wp, 'smoke_rules ' + module, 'c2_smoke_check.py', 'existing', 'named once'))
            continue
        seen.add(module)
        rows.append((wp, module))
        report.append((wp, 'smoke_rules ' + module, 'c2_smoke_check.py', 'landed', 'FUSION_RULES'))
    return rows, report


def overlay_rows(plan, text, root):
    """([(wp, path, reason)] to add, report): paths the manifest already names outside the block are not repeated; a missing file is refused."""
    present = set()
    for raw in outside(text).split('\n'):
        line = raw.split('#', 1)[0].strip()
        if line:
            present.add(line.split()[0])
    rows, report, seen = [], [], set()
    for wp, path, reason in plan['image_files']:
        if not path.startswith(IMAGE_ROOTS) or path.endswith('/'):
            raise ManifestError('%s: image file %s must be a file under %s' % (wp, path, ' or '.join(IMAGE_ROOTS)))
        if not (Path(root) / path).is_file():
            raise ManifestError('%s: image file %s is not in the tree (commit it, or drop it from the manifest)' % (wp, path))
        if path in present:
            report.append((wp, 'image ' + path, 'docker/qwen-c2-overlay.txt', 'existing', 'already listed'))
        elif path in seen:
            report.append((wp, 'image ' + path, 'docker/qwen-c2-overlay.txt', 'existing', 'listed once for another package'))
        else:
            seen.add(path)
            rows.append((wp, path, reason))
            report.append((wp, 'image ' + path, 'docker/qwen-c2-overlay.txt', 'landed', path))
    return rows, report


def overlay_block(rows):
    lines = []
    for wp, path, reason in rows:
        lines.append('# %s: %s' % (wp, ' '.join(reason.split())))
        lines.append(path)
    return lines


def suite_step(text):
    """The regression step's lines of the workflow (what the any-ref CPU suite runs), as test_w2_switch cuts it."""
    start = text.find(SUITE_STEP)
    end = text.find('\n  lever-n:', start)
    return text[start:end if end != -1 else len(text)]


def cpu_rows(plan, text, root):
    present = suite_step(outside(text))
    modules = set(re.findall(r'\btest_[A-Za-z0-9_]+', present))
    by_wp, report, seen = [], [], set()
    order = []
    for wp, module, reason in plan['tests']:
        if wp not in order:
            order.append(wp)
        by_wp.append((wp, module, reason))
    rows = []
    for wp in order:
        words, discovers = [], []
        for owner, module, reason in by_wp:
            if owner != wp:
                continue
            if isinstance(module, tuple):
                _kind, directory, pattern = module
                if not (Path(root) / directory).is_dir():
                    raise ManifestError('%s: test directory %s is not in the tree' % (wp, directory))
                line = "python -B -m unittest discover -s %s -p '%s'" % (directory, pattern)
                if line in suite_step(outside(text)) or line in discovers:
                    report.append((wp, 'tests ' + directory, 'qwen-integration-cpu.yml', 'existing', 'already allowlisted'))
                else:
                    discovers.append(line)
                    report.append((wp, 'tests ' + directory, 'qwen-integration-cpu.yml', 'landed', line))
                continue
            stem = module.split('.')[0]
            if not (Path(root) / 'scripts' / 'ci' / (stem + '.py')).is_file():
                raise ManifestError('%s: test module %s is not in scripts/ci (commit it, or drop it from the manifest)' % (wp, stem))
            if stem in modules or stem in seen:
                report.append((wp, 'tests ' + module, 'qwen-integration-cpu.yml', 'existing', 'already allowlisted'))
            else:
                seen.add(stem)
                words.append(module)
                report.append((wp, 'tests ' + module, 'qwen-integration-cpu.yml', 'landed', module))
        if words:
            rows.append((wp, 'python -B -m unittest ' + ' '.join(words)))
        rows.extend((wp, line) for line in discovers)
    return rows, report


def cpu_block(rows):
    lines = []
    last = None
    for wp, line in rows:
        if wp != last:
            lines.append('# %s' % wp)
            last = wp
        lines.append(line)
    return lines


def address_blocks(plan, root, text):
    """({block name: [lines]}, report) for the four fenced blocks of tp_addresses.py. The twin module (or the gate's module) must be in scripts/ci; the pinned
    original it replaces is the fast path's own and is not looked for."""
    blocks = {key: [] for key in TP_KEYS}
    report = []
    static = outside(text)
    for key in TP_KEYS:
        for wp, row, _reason in plan['tp'][key]:
            if key == 'twins':
                needed, line, label = row[2], '%r,  # %s' % (tuple(row), wp), '.'.join(row[:2])
            elif key == 'module_twins':
                needed, line, label = row[1], '%r,  # %s' % (tuple(row), wp), row[0]
            else:
                needed = row['gate'].split(':')[0]
                owner = repr(row['key'] if len(row['key']) > 1 else row['key'][0])
                line, label = '%s: (%r, _fusion_gate(%r)),  # %s' % (owner, row['flag'], row['gate'], wp), '.'.join(row['key'])
            if not (Path(root) / 'scripts' / 'ci' / (needed + '.py')).is_file():
                raise ManifestError('%s: tp_addresses names the module %s, which is not in scripts/ci' % (wp, needed))
            if key in ('twins', 'module_twins') and line.split('  #')[0].rstrip(',') in static:
                report.append((wp, 'tp_addresses %s %s' % (key, label), 'tp_addresses.py', 'existing', 'already a row'))
                continue
            blocks[key].append(line)
            report.append((wp, 'tp_addresses %s %s' % (key, label), 'tp_addresses.py', 'landed', key))
    return blocks, report


def replace_named_block(text, name, body, where):
    """replace_block for tp_addresses.py, which fences four blocks: the marker line carries the block's name after the end marker's text."""
    lines = text.split('\n')
    begin_at = [i for i, line in enumerate(lines) if line.strip().startswith('#') and BEGIN in line and line.strip().endswith('[%s]' % name)]
    if len(begin_at) != 1:
        raise ManifestError('%s: needs exactly one "# %s [%s]" line (%d found)' % (where, BEGIN, name, len(begin_at)))
    start = begin_at[0]
    stop = next((i for i in range(start + 1, len(lines)) if lines[i].strip().startswith('#') and lines[i].strip().lstrip('#').strip() == END), None)
    if stop is None:
        raise ManifestError('%s: the block [%s] has no "# %s" line' % (where, name, END))
    indent = lines[start][:len(lines[start]) - len(lines[start].lstrip())]
    return '\n'.join(lines[:start + 1] + [indent + line for line in body] + lines[stop:])


# ---- the whole generation ----

TARGETS = ('profiles', 'smoke', 'overlay', 'cpu', 'addresses')


def generate(texts, plan, root=REPO):
    """({target: new text}, report) from the current texts of the five files; `texts` has the keys of TARGETS. Pure: nothing is written."""
    data = json.loads(texts['profiles'])
    out = {'profiles': render_profiles(generate_profiles(data, plan))}
    report = []
    for twin in profile_twins(plan):
        report.append((twin['wp'], 'profile ' + twin['name'], 'qwen_c2_profiles.json', 'landed', twin['kind']))
    levers, audits, smoke_report = smoke_rows(plan, texts['smoke'])
    rules, rules_report = rule_rows(plan, root)
    out['smoke'] = replace_block(texts['smoke'], smoke_block(levers, audits, rules), 'c2_smoke_check.py')
    report += smoke_report + rules_report
    rows, overlay_report = overlay_rows(plan, texts['overlay'], root)
    out['overlay'] = replace_block(texts['overlay'], overlay_block(rows), 'docker/qwen-c2-overlay.txt')
    report += overlay_report
    cpu, cpu_report = cpu_rows(plan, texts['cpu'], root)
    out['cpu'] = replace_block(texts['cpu'], cpu_block(cpu), '.github/workflows/qwen-integration-cpu.yml')
    report += cpu_report
    blocks, address_report = address_blocks(plan, root, texts['addresses'])
    text = texts['addresses']
    for key in TP_KEYS:
        text = replace_named_block(text, key, blocks[key], 'tp_addresses.py')
    out['addresses'] = text
    report += address_report
    return out, report


def read_texts():
    return dict(profiles=PROFILES.read_text(encoding='utf-8'), smoke=SMOKE.read_text(encoding='utf-8'), overlay=OVERLAY.read_text(encoding='utf-8'),
                cpu=CPU_WORKFLOW.read_text(encoding='utf-8'), addresses=ADDRESSES.read_text(encoding='utf-8'))


PATHS = dict(profiles=PROFILES, smoke=SMOKE, overlay=OVERLAY, cpu=CPU_WORKFLOW, addresses=ADDRESSES)


def validate(new, root=REPO):
    """Refuse a generation the repo's own readers would refuse: the overlay parser, the profiles file, python and YAML syntax."""
    import c2_overlay

    try:
        c2_overlay.parse_manifest(new['overlay'])
    except c2_overlay.ManifestError as error:
        raise ManifestError('docker/qwen-c2-overlay.txt would be refused by c2_overlay: %s' % error)
    json.loads(new['profiles'])
    for name in ('smoke', 'addresses'):
        compile(new[name], str(PATHS[name]), 'exec')
    try:
        import yaml
    except ImportError:
        return
    yaml.safe_load(new['cpu'])


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--write', action='store_true')
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--report', action='store_true')
    parser.add_argument('--manifests', default=str(MANIFESTS))
    arguments = parser.parse_args(argv)
    if not (arguments.write or arguments.check or arguments.report):
        parser.error('--write, --check or --report')
    try:
        plan = normalise(read_manifests(arguments.manifests))
        current = read_texts()
        new, report = generate(current, plan)
        validate(new)
    except ManifestError as error:
        sys.stderr.write('make_fusion_profiles: %s\n' % error)
        return 2
    if arguments.report:
        for wp, item, target, status, where in report:
            print('%s | %s | %s | %s | %s' % (wp, item, target, status, where))
    stale = [name for name in TARGETS if new[name] != current[name]]
    if arguments.check:
        for name in stale:
            sys.stderr.write('%s is not what make_fusion_profiles.py generates from scripts/ci/fusion-wp: run it with --write\n' % PATHS[name])
        return 1 if stale else 0
    if arguments.write:
        for name in stale:
            with open(str(PATHS[name]), 'w', encoding='utf-8', newline='\n') as handle:
                handle.write(new[name])
    return 0


if __name__ == '__main__':
    sys.exit(main())
