"""The op-fusion programme's card pack (scripts/ci/references/fusion-jobs, generated by make_fusion_jobs.py from the work packages' manifests).

Holds: the checked-in pack is what the manifests in the tree generate; ORDER.txt lists exactly the pack's templates, each once, one image tag, positive minutes, a total that matches its
header, only B0 and X0 stop the window; every template parses through the job reader with rc 0 (the command-line reader too); B0 bakes the profile production runs; for a set of
synthetic manifests, each merged lever gets an audited attach, a timed ABAB at eight live and one common Z, the audits of every lever run before any timed pair, the lever twins are
the production profile plus exactly the flags, the NEEDS lines name earlier jobs, and the pack names no host, address, registry or home path (the repo is public)."""

import json
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import unittest

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

import c2_serving_job as job  # noqa: E402
import make_fusion_jobs as jobs_gen  # noqa: E402
import make_fusion_profiles as fusion  # noqa: E402

FOLDER = HERE / 'references' / 'fusion-jobs'
IMAGE = jobs_gen.IMAGE
SHIP = fusion.PARENT
READER = HERE / 'c2_serving_job.py'

MANIFESTS = {
    'WP1.json': {'wp': 'WP1', 'levers': [{'id': 's1', 'name': 'S1 shard argmax', 'flag': 'QWEN_FAST_TP4_SHARD_ARGMAX', 'audit_flag': 'QWEN_FAST_TP4_SHARD_ARGMAX_AUDIT',
                                          'marker': 'tp4 shard argmax', 'reason': 'one scan over the shard'}]},
    'WP5.json': {'wp': 'WP5', 'levers': [{'id': 'ccl', 'name': 'CCL options', 'flag': 'QWEN_FAST_TP4_CCL_OPTIONS', 'value': 'rs2', 'marker': 'tp4 ccl options',
                                          'reason': 'per-call collective options'}]},
    'WP7.json': {'wp': 'WP7', 'levers': [{'id': 'dperm', 'name': 'drafter permutations', 'flag': 'QWEN_FAST_TP4_DRAFT_PERMUTE',
                                          'audit_flag': 'QWEN_FAST_TP4_DRAFT_PERMUTE_AUDIT', 'marker': 'tp4 draft permute', 'reason': 'K/V assembly as one kernel'}]},
}


def plan_of(manifests):
    directory = Path(tempfile.mkdtemp(prefix='fusion-jobs-'))
    for name, raw in manifests.items():
        (directory / name).write_text(json.dumps(raw), encoding='utf-8')
    return fusion.normalise(fusion.read_manifests(directory))


def profiles_file(plan):
    """A profiles file holding the plan's twins (the real file holds them only once the packages are merged)."""
    out, _report = fusion.generate(fusion.read_texts(), plan, fusion.REPO)
    path = Path(tempfile.mkdtemp(prefix='fusion-profiles-')) / 'profiles.json'
    path.write_text(out['profiles'], encoding='utf-8')
    return path


def pack_of(plan):
    folder = Path(tempfile.mkdtemp(prefix='fusion-pack-'))
    for name, text in jobs_gen.generate(plan, folder).items():
        (folder / name).write_text(text, encoding='utf-8')
    return folder


def order_lines(folder):
    text = (folder / 'ORDER.txt').read_text(encoding='utf-8')
    return [line.split() for line in text.splitlines() if line.strip() and not line.startswith('#')]


def values(folder, name):
    return job.parse_env((folder / (name + '.env')).read_text(encoding='utf-8'))


def short(name):
    return name.split('-', 1)[0]


PLAN = plan_of(MANIFESTS)
PROFILES = profiles_file(PLAN)
PACK = pack_of(PLAN)


class CheckedInTests(unittest.TestCase):
    def test_the_checked_in_pack_is_what_the_manifests_in_the_tree_generate(self):
        wanted = jobs_gen.generate(fusion.normalise(fusion.read_manifests()), FOLDER)
        self.assertEqual(jobs_gen.stale(FOLDER, wanted), [])
        self.assertEqual(jobs_gen.main(['--check']), 0)

    def test_every_checked_in_template_passes_the_job_reader(self):
        profiles = job.profile_names(str(fusion.PROFILES))
        envs = job.profile_envs(str(fusion.PROFILES))
        names = [path for path in sorted(FOLDER.glob('*.env'))]
        self.assertTrue(names)
        for path in names:
            with self.subTest(path.name):
                outputs = job.read_job(job.parse_env(path.read_text(encoding='utf-8')), profiles, envs=envs)
                self.assertTrue(outputs['actions'])

    def test_every_checked_in_template_exits_zero_through_the_command_line_reader(self):
        for path in sorted(FOLDER.glob('*.env')):
            result = subprocess.run([sys.executable, '-s', str(READER), str(path), str(fusion.PROFILES)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=str(HERE.parent.parent))
            self.assertEqual(result.returncode, 0, path.name + ' ' + result.stderr.decode('utf-8', 'replace'))

    def test_the_checked_in_order_lists_exactly_the_templates(self):
        lines = order_lines(FOLDER)
        self.assertEqual(sorted(line[0] for line in lines), sorted(path.stem for path in FOLDER.glob('*.env')))
        self.assertEqual(len(set(line[0] for line in lines)), len(lines))
        self.assertEqual(lines[0][0], 'B0-build')
        self.assertEqual(lines[-1][0], 'Z-reset')


class SyntheticPackTests(unittest.TestCase):
    def test_the_order_is_b0_x0_every_audit_every_abab_then_z(self):
        names = [short(line[0]) for line in order_lines(PACK)]
        self.assertEqual(names, ['B0', 'X0', 'S1A', 'DPERMA',
                                 'S1C1', 'S1L1', 'S1C2', 'S1L2',
                                 'CCLC1', 'CCLL1', 'CCLC2', 'CCLL2',
                                 'DPERMC1', 'DPERML1', 'DPERMC2', 'DPERML2', 'Z'])

    def test_the_order_lists_exactly_the_templates_with_one_image_and_positive_minutes(self):
        lines = order_lines(PACK)
        self.assertEqual(sorted(line[0] for line in lines), sorted(path.stem for path in PACK.glob('*.env')))
        for name, mode, image, minutes in lines:
            self.assertEqual((image, mode in ('stop', 'soft'), int(minutes) > 0), (IMAGE, True, True), name)
        self.assertEqual([line[0] for line in lines if line[1] == 'stop'], ['B0-build', 'X0-status-rescan-reset'])

    def test_the_total_in_the_header_is_the_sum(self):
        text = (PACK / 'ORDER.txt').read_text(encoding='utf-8')
        lines = order_lines(PACK)
        total = sum(int(line[3]) for line in lines)
        self.assertIn('%d minutes (%d h %d min) in all' % (total, total // 60, total % 60), text)
        repeats = sum(int(line[3]) for line in lines if re.match(r'^[A-Z0-9]+(C2|L2)-', line[0]))
        self.assertIn('%d minutes without the repeat pairs' % (total - repeats), text)
        self.assertIn('%d minutes of cards' % (total - 40), text)

    def test_every_template_exits_zero_through_the_job_reader_and_the_command_line(self):
        profiles = job.profile_names(str(PROFILES))
        envs = job.profile_envs(str(PROFILES))
        for path in sorted(PACK.glob('*.env')):
            with self.subTest(path.name):
                outputs = job.read_job(job.parse_env(path.read_text(encoding='utf-8')), profiles, envs=envs)
                self.assertTrue(outputs['actions'])
                result = subprocess.run([sys.executable, '-s', str(READER), str(path), str(PROFILES)], stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                                        cwd=str(HERE.parent.parent))
                self.assertEqual(result.returncode, 0, result.stderr.decode('utf-8', 'replace'))

    def test_b0_builds_the_one_image_and_bakes_the_profile_production_runs(self):
        b0 = values(PACK, 'B0-build')
        self.assertEqual((b0['C2_ACTIONS'], b0['C2_PROFILE'], b0['C2_IMAGE_TAG']), ('build', 'c2-packed-tp4', IMAGE))
        self.assertEqual(b0['C2_BAKE_DEFAULT_PROFILE'], SHIP)
        window = job.parse_env((HERE / 'references' / 'tp4-octo2-jobs' / 'B0-build.env').read_text(encoding='utf-8'))
        self.assertEqual(b0['C2_BAKE_DEFAULT_PROFILE'], window['C2_BAKE_DEFAULT_PROFILE'])
        self.assertEqual([line[0] for line in order_lines(PACK) if values(PACK, line[0])['C2_ACTIONS'] == 'build'], ['B0-build'])

    def test_every_job_serves_the_one_image(self):
        for path in PACK.glob('*.env'):
            self.assertEqual(job.parse_env(path.read_text(encoding='utf-8'))['C2_IMAGE_TAG'], IMAGE, path.name)

    def test_each_job_selects_the_profile_its_generator_makes(self):
        twins = json.loads(PROFILES.read_text(encoding='utf-8'))['profiles']
        for lever in PLAN['levers']:
            prefix = lever['id'].upper()
            timed, audited = fusion.twin_id(lever, False), fusion.twin_id(lever, True)
            self.assertIn(timed, twins)
            self.assertEqual([values(PACK, name)['C2_PROFILE'] for name in sorted(path.stem for path in PACK.glob(prefix + 'C*.env'))], [SHIP, SHIP])
            self.assertEqual([values(PACK, name)['C2_PROFILE'] for name in sorted(path.stem for path in PACK.glob(prefix + 'L*.env'))], [timed, timed])
            audit_jobs = sorted(path.stem for path in PACK.glob(prefix + 'A-*.env'))
            if lever['audit_flag']:
                self.assertEqual([values(PACK, name)['C2_PROFILE'] for name in audit_jobs], [audited])
                self.assertEqual(twins[audited]['env'][lever['audit_flag']], '1')
                self.assertNotIn(lever['audit_flag'], twins[timed]['env'])
            else:
                self.assertEqual(audit_jobs, [], 'a lever with no audit flag has no audited attach')
        used = set(values(PACK, line[0]).get('C2_PROFILE') for line in order_lines(PACK)) - {None, 'c2-packed-tp4'}
        self.assertEqual(used, set(twin for twin in fusion.twin_names(self.manifests_dir())) | {SHIP})

    def manifests_dir(self):
        directory = Path(tempfile.mkdtemp(prefix='fusion-jobs-m-'))
        for name, raw in MANIFESTS.items():
            (directory / name).write_text(json.dumps(raw), encoding='utf-8')
        return directory

    def test_a_lever_twin_is_the_production_profile_plus_exactly_its_flag(self):
        twins = json.loads(PROFILES.read_text(encoding='utf-8'))['profiles']
        parent = twins[SHIP]
        for lever in PLAN['levers']:
            mine = twins[fusion.twin_id(lever, False)]
            self.assertEqual({k: v for k, v in mine['env'].items() if parent['env'].get(k) != v}, {lever['flag']: lever['value']})
            self.assertTrue(set(parent['env']) <= set(mine['env']))
            self.assertIs(mine['gate_only'], True)

    def test_all_the_timed_jobs_run_the_same_tests_and_include_concurrent8_steady(self):
        for line in order_lines(PACK):
            tests = values(PACK, line[0]).get('C2_SMOKE_TESTS')
            if line[0].startswith(('B0', 'X0', 'Z')):
                self.assertFalse(tests, line[0])
            else:
                self.assertEqual(tests, 'warmup,concurrent8_steady', line[0])
                self.assertIn('concurrent8_steady', tests.split(','))

    def test_the_timed_jobs_alternate_control_lever_control_lever_on_one_image(self):
        for prefix in ('S1', 'CCL', 'DPERM'):
            names = [line[0] for line in order_lines(PACK) if re.match('^%s(C|L)[12]-' % prefix, line[0])]
            kinds = ['control' if re.match('^%sC' % prefix, name) else 'lever' for name in names]
            self.assertEqual(kinds, ['control', 'lever', 'control', 'lever'], prefix)
            profiles = [values(PACK, name)['C2_PROFILE'] for name in names]
            self.assertEqual(profiles[0], profiles[2])
            self.assertEqual(profiles[1], profiles[3])
            self.assertNotEqual(profiles[0], profiles[1])

    def test_the_needs_lines_name_known_jobs_that_run_earlier_and_gate_each_lever_on_its_audit(self):
        text = (PACK / 'ORDER.txt').read_text(encoding='utf-8')
        position = dict((short(line[0]), index) for index, line in enumerate(order_lines(PACK)))
        needs = re.findall(r'^# NEEDS (.+?) <- (.+)$', text, re.M)
        waiting = {}
        for left, right in needs:
            for name in left.split():
                self.assertIn(name, position, name)
                waiting[name] = right.split()
                for needed in right.split():
                    self.assertIn(needed, position, needed)
                    self.assertLess(position[needed], position[name], '%s needs %s, which runs later' % (name, needed))
        for name in position:
            if name not in ('B0', 'Z'):
                self.assertIn(name, waiting, name)
        self.assertEqual(waiting['S1L1'], ['S1A', 'S1C1'])
        self.assertEqual(waiting['CCLL1'], ['CCLC1'], 'a lever with no audit flag needs its control only')
        self.assertEqual(waiting['S1L2'], ['S1C2'])
        self.assertEqual(waiting['X0'], ['B0'])

    def test_the_read_rules_name_tools_that_exist(self):
        text = (PACK / 'ORDER.txt').read_text(encoding='utf-8') + ''.join(path.read_text(encoding='utf-8') for path in PACK.glob('*.env'))
        for tool in ('w2ln_timing_compare.py', 'c2_smoke_check'):
            self.assertIn(tool.split('.')[0], text)
        self.assertTrue((HERE / 'w2ln_timing_compare.py').exists())
        self.assertTrue((HERE / 'c2_smoke_check.py').exists())
        compare = (HERE / 'w2ln_timing_compare.py').read_text(encoding='utf-8')
        for word in ("sub.add_parser('pair'", "sub.add_parser('floor'", "'steady'", '--a-smoke'):
            self.assertIn(word, compare)

    def test_no_job_starts_the_node_agent_or_pushes_a_tag(self):
        for line in order_lines(PACK):
            actions = values(PACK, line[0])['C2_ACTIONS'].split()
            self.assertFalse({'agent', 'start', 'serve', 'deploy'} & set(actions), line[0])

    def test_two_levers_with_one_job_prefix_are_refused(self):
        manifests = dict(MANIFESTS)
        manifests['WP2.json'] = {'wp': 'WP2', 'levers': [{'id': 's-1', 'name': 'x', 'flag': 'QWEN_FAST_TP4_X', 'marker': 'tp4 x'}]}
        with self.assertRaises(fusion.ManifestError) as caught:
            jobs_gen.generate(plan_of(manifests))
        self.assertIn('same job prefix S1', str(caught.exception))

    def test_a_stale_template_is_reported_and_removed_by_write(self):
        folder = pack_of(PLAN)
        (folder / 'OLD-stale.env').write_text('C2_CARDS=quad\n', encoding='utf-8')
        wanted = jobs_gen.generate(PLAN, folder)
        self.assertEqual(jobs_gen.stale(folder, wanted), ['OLD-stale.env'])
        self.assertEqual(jobs_gen.main(['--write', '--folder', str(folder), '--manifests', str(self.manifests_dir())]), 0)
        self.assertFalse((folder / 'OLD-stale.env').exists())
        self.assertEqual(jobs_gen.stale(folder, wanted), [])


ARM_MANIFESTS = {
    'WP1.json': {'wp': 'WP1', 'levers': [{'id': 's1', 'name': 'S1 shard argmax', 'flag': 'QWEN_FAST_TP4_SHARD_ARGMAX', 'audit_flag': 'QWEN_FAST_TP4_SHARD_ARGMAX_AUDIT',
                                          'marker': 'tp4 shard argmax', 'reason': 'one scan'}],
                 'profiles': [{'name': 's1f2', 'env': {'QWEN_FAST_TP4_SHARD_ARGMAX': '1', 'QWEN_FAST_TP4_SHARD_ARGMAX_FOLD2': '1'}, 'reason': 'tree fold'},
                              {'name': 's1f2-audit', 'audit': True, 'reason': 'tree fold audited',
                               'env': {'QWEN_FAST_TP4_SHARD_ARGMAX': '1', 'QWEN_FAST_TP4_SHARD_ARGMAX_FOLD2': '1', 'QWEN_FAST_TP4_SHARD_ARGMAX_AUDIT': '1'}}]},
    'WP6.json': {'wp': 'WP6', 'profiles': [{'name': 'dr-x', 'env': {'QWEN_FAST_TP4_DRAFT_REDUCE': '1'}, 'reason': 'x'},
                                           {'name': 'dr-solo-audit', 'audit': True, 'env': {'QWEN_FAST_TP4_DRAFT_REDUCE': '1', 'QWEN_FAST_TP4_DRAFT_REDUCE_AUDIT': '1'},
                                            'reason': 'an audit with no timed twin'}]},
}


class ArmTests(unittest.TestCase):
    """The extra profile twins of a package (a variant of a lever, a combination) are arms of the pack too."""

    @classmethod
    def setUpClass(cls):
        cls.plan = plan_of(ARM_MANIFESTS)
        cls.profiles = profiles_file(cls.plan)
        cls.pack = pack_of(cls.plan)

    def test_a_profile_twin_and_its_audit_twin_are_one_arm_with_an_audited_attach_and_an_abab(self):
        names = [short(line[0]) for line in order_lines(self.pack)]
        self.assertEqual(names, ['B0', 'X0', 'S1A', 'S1F2A', 'DRSOLOA',
                                 'S1C1', 'S1L1', 'S1C2', 'S1L2', 'S1F2C1', 'S1F2L1', 'S1F2C2', 'S1F2L2', 'DRXC1', 'DRXL1', 'DRXC2', 'DRXL2', 'Z'])
        twins = json.loads(self.profiles.read_text(encoding='utf-8'))['profiles']
        self.assertEqual(values(self.pack, 'S1F2A-s1f2-audit-attach')['C2_PROFILE'], fusion.NAMESPACE + 's1f2-audit')
        self.assertEqual(values(self.pack, 'S1F2L1-s1f2-lever-timed')['C2_PROFILE'], fusion.NAMESPACE + 's1f2')
        self.assertEqual(values(self.pack, 'S1F2C2-s1f2-control-repeat')['C2_PROFILE'], SHIP)
        self.assertEqual(twins[fusion.NAMESPACE + 's1f2']['env']['QWEN_FAST_TP4_SHARD_ARGMAX_FOLD2'], '1')

    def test_the_needs_lines_gate_each_arm_on_its_own_audit_and_an_audit_only_arm_has_no_timing(self):
        text = (self.pack / 'ORDER.txt').read_text(encoding='utf-8')
        needs = dict((left, right.split()) for left, right in re.findall(r'^# NEEDS (.+?) <- (.+)$', text, re.M))
        self.assertEqual(needs['S1F2L1'], ['S1F2A', 'S1F2C1'])
        self.assertEqual(needs['DRXL1'], ['DRXC1'], 'a timed twin with no audit twin needs its control only')
        self.assertEqual(needs['DRSOLOA'], ['X0'])
        self.assertFalse([name for name in needs if name.startswith('DRSOLOC') or name.startswith('DRSOLOL')])

    def test_every_template_exits_zero_through_the_command_line_reader(self):
        for path in sorted(self.pack.glob('*.env')):
            result = subprocess.run([sys.executable, '-s', str(READER), str(path), str(self.profiles)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=str(HERE.parent.parent))
            self.assertEqual(result.returncode, 0, path.name + ' ' + result.stderr.decode('utf-8', 'replace'))

    def test_two_arms_with_one_prefix_are_refused(self):
        manifests = dict(ARM_MANIFESTS)
        manifests['WP2.json'] = {'wp': 'WP2', 'profiles': [{'name': 's-1f2', 'env': {'QWEN_FAST_TP4_X': '1'}, 'reason': 'x'}]}
        with self.assertRaises(fusion.ManifestError) as caught:
            jobs_gen.generate(plan_of(manifests), FOLDER)
        self.assertIn('same job prefix S1F2', str(caught.exception))

    def test_the_order_names_the_packages_own_folders_inside_and_beside_the_pack(self):
        references = Path(tempfile.mkdtemp(prefix='fusion-refs-'))
        folder = references / 'fusion-jobs'
        folder.mkdir()
        (folder / 'WP9').mkdir()
        (references / 'fusion-jobs-wp5').mkdir()
        (references / 'fusion-wp7-jobs').mkdir()
        (references / 'tp4-octo2-jobs').mkdir()
        self.assertEqual(jobs_gen.package_folders(folder), ['fusion-jobs-wp5', 'fusion-jobs/WP9', 'fusion-wp7-jobs'])
        text = jobs_gen.generate(self.plan, folder)['ORDER.txt']
        self.assertIn('under references/): fusion-jobs-wp5, fusion-jobs/WP9, fusion-wp7-jobs.', text)
        self.assertNotIn('tp4-octo2-jobs', text)
        self.assertIn('under references/): none yet.', jobs_gen.generate(self.plan, Path(tempfile.mkdtemp()) / 'fusion-jobs')['ORDER.txt'])


class PackageFolderTests(unittest.TestCase):
    """A package's own templates (references/fusion-jobs/<WP>/), written against the profiles the generator places: each exits zero through the reader."""

    @staticmethod
    def folders():
        """The packages' own template folders: inside the pack and the `fusion-*` folders beside it."""
        return [FOLDER.parent / name.split('/')[-1] if '/' not in name else FOLDER / name.split('/')[-1] for name in jobs_gen.package_folders(FOLDER)]

    def test_every_template_of_every_package_folder_exits_zero(self):
        folders = self.folders()
        for folder in folders:
            for path in sorted(folder.glob('*.env')):
                with self.subTest('%s/%s' % (folder.name, path.name)):
                    result = subprocess.run([sys.executable, '-s', str(READER), str(path), str(fusion.PROFILES)], stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                                            cwd=str(HERE.parent.parent))
                    self.assertEqual(result.returncode, 0, result.stderr.decode('utf-8', 'replace'))

    def test_every_package_template_names_the_one_image(self):
        for folder in self.folders():
            for path in sorted(folder.glob('*.env')):
                self.assertEqual(job.parse_env(path.read_text(encoding='utf-8'))['C2_IMAGE_TAG'], IMAGE, '%s/%s' % (folder.name, path.name))


class PublicTests(unittest.TestCase):
    @staticmethod
    def package_folders():
        return PackageFolderTests.folders()

    def test_the_pack_names_no_host_address_registry_or_home_path(self):
        pattern = re.compile(r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}|/home/|/Users/|[A-Za-z]:[\\/]|\.local\b|\.lan\b|\bssh\b|ghcr\.io|docker\.io|sha256:[0-9a-f]{12}|spark-|thatch@')
        for folder in [FOLDER, PACK] + self.package_folders():
            for path in sorted(folder.rglob('*')):
                if path.is_dir():
                    continue
                text = path.read_text(encoding='utf-8')
                with self.subTest(path.name):
                    self.assertIsNone(pattern.search(text), pattern.search(text) and pattern.search(text).group(0))
                    self.assertNotIn('\r', text)


if __name__ == '__main__':
    unittest.main()
