"""The op-fusion programme's COMBINED twins (docs/tp4-fusion.md): `...-w2-er-fx-all` (every lever that is exact by construction on together) and `...-fx-all-audit` (plus every
lever's _AUDIT flag), generated by make_fusion_profiles.py from the combined entry of fusion-wp/WP0.json.

Held, for both twins:
  - the twin is the production profile plus exactly the levers' flags (and nothing of the two levers that wait for a card: the K/V page writer, the fused MLP gate|up);
  - the profile passes serving_c2_contract's boot checks as a gate run (every check boot() makes before it touches the environment), and the environment it builds is accepted by
    every package's strict validator at once: the shard-argmax pair with its tree fold, the drafter levers, the CCL options (whose reduce-scatter tokens need the unit-major lever the
    parent carries), the MLP configuration, the engine-start upload levers, the sampdraft pairing;
  - every flag of the twin has a row in the smoke tables (the generated ones or the static ones) at the value it carries, so a boot that runs the combination is judged lever by lever;
  - the audited twin differs from the timed twin by the audit flags and nothing else;
  - the combined card pack (references/fusion-jobs/combined) is the audited attach and the timed ABAB of exactly these two twins, and every template exits zero through the job reader.

    py -3.11 -B -m unittest test_fusion_combined      (from scripts/ci)
"""

import json
import os
from pathlib import Path
import subprocess
import sys
import unittest
from unittest.mock import patch

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

import c2_serving_job as job  # noqa: E402
import c2_smoke_check  # noqa: E402
import make_fusion_jobs as jobs_gen  # noqa: E402
import make_fusion_profiles as fusion  # noqa: E402
import serving_c2_contract as contract  # noqa: E402

PROFILES = json.loads((HERE / 'qwen_c2_profiles.json').read_text(encoding='utf-8'))['profiles']
PLAN = fusion.normalise(fusion.read_manifests())
SPEC = next(spec for spec in PLAN['combined'] if spec['name'] == 'all')
TIMED, AUDITED = fusion.NAMESPACE + 'all', fusion.NAMESPACE + 'all-audit'
PARENT = PROFILES[fusion.PARENT]
PACK = HERE / 'references' / 'fusion-jobs' / 'combined'

SWITCHED_ON = {
    'QWEN_FAST_DRAFT_PERMUTE': '1', 'QWEN_FAST_TP4_SHARD_ARGMAX': '1', 'QWEN_FAST_TP4_SHARD_ARGMAX_FOLD2': '1', 'QWEN_FAST_DRAFT_REDUCE': '1', 'QWEN_FAST_DRAFT_QKV1': '1',
    'QWEN_FAST_DRAFT_TAIL': '1', 'QWEN_FAST_DRAFT_GATEUP1': '1', 'QWEN_FAST_DRAFT_MM_GRID': '1', 'QWEN_FAST_DRAFT_HEAD64': '1', 'QWEN_FAST_CCL_OPTIONS': 'rs-c1',
    'QWEN_FAST_MLP_CFG': 'g3u4d3', 'QWEN_FAST_KV_PAGE_WRITER': '1',
    'QWEN_FAST_TP4_ROUND_HOST_SELECT': '1', 'QWEN_FAST_TP4_ROUND_HOST_READ': '1', 'QWEN_FAST_TP4_ROUND_HOST_KEYED': '1', 'QWEN_FAST_TP4_ROUND_HOST_LEAN': '1', 'QWEN_FAST_DEVICE_ZEROS': '1', 'QWEN_FAST_LAZY_SHARD_W': '1'}
AUDIT_FLAGS = {
    'QWEN_FAST_DRAFT_PERMUTE_AUDIT': '1', 'QWEN_FAST_TP4_SHARD_ARGMAX_AUDIT': '1', 'QWEN_FAST_DRAFT_REDUCE_AUDIT': '1', 'QWEN_FAST_DRAFT_QKV1_AUDIT': '1',
    'QWEN_FAST_DRAFT_TAIL_AUDIT': '1', 'QWEN_FAST_DRAFT_GATEUP1_AUDIT': '1', 'QWEN_FAST_DRAFT_MM_GRID_AUDIT': '1', 'QWEN_FAST_DRAFT_HEAD64_AUDIT': '1',
    'QWEN_FAST_CCL_OPTIONS_AUDIT': '1', 'QWEN_FAST_MLP_CFG_AUDIT': '1', 'QWEN_FAST_KV_PAGE_WRITER_AUDIT': '1', 'QWEN_FAST_TP4_ROUND_HOST_AUDIT': '1', 'QWEN_FAST_DEVICE_ZEROS_AUDIT': '1', 'QWEN_FAST_LAZY_SHARD_W_AUDIT': '1'}
WAITING = ('QWEN_FAST_MLP_GATEUP',)      # the fused MLP gate|up (exact but slower on the card: NO-GO)


def additions(name):
    return {key: value for key, value in PROFILES[name]['env'].items() if PARENT['env'].get(key) != value}


def gate_environment(profile):
    """The process environment of a gate run of `profile`, as boot() builds it."""
    environ = {'QWEN_C2_SERVING': '1', contract.GATE_SWITCH: '1', 'QWEN_C2_GATE_PROFILE': '1'}
    contract.apply_environment(profile, environ)
    return environ


class TwinShapeTests(unittest.TestCase):
    def test_the_timed_twin_is_the_production_profile_plus_exactly_the_levers_on(self):
        self.assertEqual(additions(TIMED), SWITCHED_ON)
        for key, value in SWITCHED_ON.items():
            self.assertNotIn(key, PARENT['env'], 'a parent never carries the lever it is twinned with: ' + key)
        for key in WAITING:
            self.assertNotIn(key, PROFILES[TIMED]['env'])
            self.assertNotIn(key + '_AUDIT', PROFILES[AUDITED]['env'])

    def test_the_audited_twin_is_the_timed_twin_plus_the_audit_flags_and_nothing_else(self):
        self.assertEqual(additions(AUDITED), dict(SWITCHED_ON, **AUDIT_FLAGS))
        self.assertEqual({k: v for k, v in PROFILES[AUDITED]['env'].items() if k not in AUDIT_FLAGS}, PROFILES[TIMED]['env'])

    def test_both_are_gate_only_copies_of_the_production_profile_without_its_waiver(self):
        for name in (TIMED, AUDITED):
            profile = dict(PROFILES[name])
            self.assertIs(profile.pop('gate_only'), True, name)
            expected = {key: value for key, value in PARENT.items() if key not in ('env', 'description', fusion.WAIVER_FIELD)}
            self.assertEqual({key: value for key, value in profile.items() if key not in ('env', 'description')}, expected, name)
            self.assertTrue(profile['description'].startswith('GATE ONLY, UNQUALIFIED (the op-fusion programme'), name)
        self.assertIn(fusion.WAIVER_FIELD, PARENT)

    def test_the_ccl_set_is_the_sweep_winner_the_lever_itself_carries(self):
        lever = next(item for item in PLAN['levers'] if item['id'] == 'ccl')
        self.assertEqual(lever['value'], 'rs-c1', 'WP5 P0 winner: chunks per sync 1 on the unit-major reduce-scatters')
        self.assertNotIn('ccl', SPEC.get('values', {}), 'no override: the combined arm carries the lever\'s own value')
        self.assertEqual(PROFILES[TIMED]['env']['QWEN_FAST_CCL_OPTIONS'], 'rs-c1')
        self.assertEqual(PROFILES[fusion.NAMESPACE + 'ccl']['env']['QWEN_FAST_CCL_OPTIONS'], lever['value'])
        self.assertEqual(PROFILES[fusion.NAMESPACE + 'ccl-served']['env']['QWEN_FAST_CCL_OPTIONS'], 'served', 'the A/A control twin keeps the served set')

    def test_the_combined_levers_are_the_ones_the_coordinator_named(self):
        self.assertEqual(SPEC['levers'], ['permute', 's1', 'reduce', 'qkv1', 'tail', 'gateup1', 'mmgrid', 'head64', 'ccl', 'mlpcfg', 'kvpage'])
        self.assertEqual(SPEC['values'], {'mlpcfg': 'g3u4d3'})
        self.assertNotIn('mlpgu', SPEC['levers'])
        self.assertIn(TIMED, fusion.twin_names())
        self.assertIn(AUDITED, fusion.twin_names())


class ContractTests(unittest.TestCase):
    def problems(self, name):
        """boot()'s checks, in its order, for a gate run of the profile."""
        profile = dict(PROFILES[name], name=name)
        environ = gate_environment(profile)
        found = []
        for check in (lambda: contract.gate_problems(profile, environ) + contract.waiver_problems(profile, environ) + contract.traffic_waiver_problems(profile),
                      lambda: contract.prefix_reuse_problems(profile), lambda: contract.levern_problems(profile), lambda: contract.multi_problems(profile),
                      lambda: contract.w2_problems(profile, environ), lambda: contract.upload_problems(profile), lambda: contract.drafter_problems(profile),
                      lambda: contract.parked_problems(profile, environ), lambda: contract.mesh_problems(profile)):
            found += check()
        return found

    def test_both_twins_pass_every_boot_check_of_the_serving_contract(self):
        for name in (TIMED, AUDITED):
            with self.subTest(profile=name):
                self.assertEqual(self.problems(name), [])

    def test_without_the_gate_switch_the_contract_refuses_them_as_gate_only(self):
        for name in (TIMED, AUDITED):
            profile = dict(PROFILES[name], name=name)
            self.assertTrue(contract.gate_problems(profile, {}), name)

    def test_the_upload_levers_are_armed_by_the_profile_and_the_environment_it_builds_carries_every_flag(self):
        for name in (TIMED, AUDITED):
            environ = gate_environment(dict(PROFILES[name], name=name))
            for key, value in additions(name).items():
                self.assertEqual(environ[key], value, (name, key))


class ValidatorTests(unittest.TestCase):
    """Every package's strict validator, on the environment of each twin."""

    def environments(self):
        for name in (TIMED, AUDITED):
            yield name, gate_environment(dict(PROFILES[name], name=name))

    def test_the_sampdraft_pairing_accepts_the_shard_argmax_with_its_tree_fold(self):
        import tp4_sampdraft

        for name, environ in self.environments():
            with self.subTest(profile=name):
                tp4_sampdraft.validate(environ)
        environ = dict(gate_environment(dict(PROFILES[TIMED], name=TIMED)))
        del environ['QWEN_FAST_TP4_SHARD_ARGMAX']
        with self.assertRaises(ValueError, msg='the tree fold without S1 is refused: the check is live'):
            tp4_sampdraft.validate(environ)

    def test_the_drafter_levers_validate_together(self):
        import draft_fusion_tp
        import draft_head64_tp
        import draft_permute_tp
        import draft_qkv_tp

        for name, environ in self.environments():
            with self.subTest(profile=name):
                draft_fusion_tp.validate(environ)
                draft_permute_tp.validate(environ)
                for module in (draft_qkv_tp, draft_head64_tp):
                    self.assertTrue(module.enabled(environ))
                    module.audit_enabled(environ)
                for flag in draft_fusion_tp.LEVERS:
                    self.assertTrue(draft_fusion_tp.enabled(flag, environ), flag)

    def test_the_branch_checks_accept_the_four_drafter_flags_beside_the_audits(self):
        import draft_mlp_branch

        for name, environ in self.environments():
            with self.subTest(profile=name), patch.dict(os.environ, environ, clear=True):
                levers = draft_mlp_branch._levers_checked()
                self.assertEqual(levers, {draft_mlp_branch.REDUCE_FLAG: True, draft_mlp_branch.TAIL_FLAG: True, draft_mlp_branch.GATEUP1_FLAG: True,
                                          draft_mlp_branch.MM_GRID_FLAG: True})

    def test_the_ccl_options_accept_the_served_set_beside_the_unit_major_reduce_scatter(self):
        import ccl_options_tp

        for name, environ in self.environments():
            with self.subTest(profile=name):
                settings = ccl_options_tp.settings(environ)
                self.assertIsNotNone(settings)
                self.assertEqual(settings.audit_calls > 0, name == AUDITED)
        self.assertEqual(PARENT['env']['QWEN_FAST_TP4_RS_UNIT_MAJOR'], '1', 'the parent carries the lever the reduce-scatter tokens ride')

    def test_the_validators_are_live_on_these_environments(self):
        """Negative controls: each cross-lever rule the combination leans on refuses its violation, so a pass above is not an empty check."""
        import ccl_options_tp
        import draft_fusion_tp

        base = gate_environment(dict(PROFILES[AUDITED], name=AUDITED))
        no_unit_major = dict(base, QWEN_FAST_CCL_OPTIONS='rs-c1', QWEN_FAST_TP4_RS_UNIT_MAJOR='0')
        with self.assertRaises(ValueError):
            ccl_options_tp.settings(no_unit_major)
        self.assertIsNotNone(ccl_options_tp.settings(dict(no_unit_major, QWEN_FAST_TP4_RS_UNIT_MAJOR='1')))
        with self.assertRaises(ValueError):
            draft_fusion_tp.validate(dict(base, QWEN_FAST_DRAFT_REDUCE='0'))              # its audit with the lever off
        with self.assertRaises(ValueError):
            draft_fusion_tp.validate(dict(base, QWEN_FAST_DRAFT_TAIL='yes'))              # a flag that is not 0 or 1
        with self.assertRaises(ValueError):
            draft_fusion_tp.validate(dict(base, QWEN_FAST_TP='2'))                        # a TP4 lever at the pair

    def test_the_mlp_configuration_resolves_and_the_fused_route_is_off(self):
        import tp4_mlp_gateup

        for name, environ in self.environments():
            with self.subTest(profile=name):
                resolved = tp4_mlp_gateup.resolve(environ)
                self.assertIsNotNone(resolved)
                self.assertFalse(tp4_mlp_gateup._read(tp4_mlp_gateup.GATEUP, environ))
                self.assertEqual(tp4_mlp_gateup._read(tp4_mlp_gateup.CFG_AUDIT, environ), name == AUDITED)

    def test_the_named_mlp_configuration_is_the_one_the_smoke_rule_judges(self):
        import tp4_mlp_gateup
        import tp4_mlp_gateup_smoke

        env = PROFILES[AUDITED]['env']
        self.assertEqual(tp4_mlp_gateup.resolve(env).name, 'g3u4d3')
        line = '[PINDIAG] tp4 mlp gateup engaged route=cfg name=%s rows=64 layers=64 g3u4d3 l1_multiply=1 audit=1 stride=1'
        audit = '[PINDIAG] tp4 mlp gateup audit route=cfg name=%s layer=0 exact=True'
        good = '\n'.join([line % 'g3u4d3', audit % 'g3u4d3'])
        self.assertEqual(tp4_mlp_gateup_smoke.problems(env, good), [])
        self.assertEqual([p for p in c2_smoke_check.fusion_problems(good, env) if 'MLP' in p or 'mlp' in p], [])
        wrong = '\n'.join([line % 'l1', audit % 'l1'])
        self.assertTrue(tp4_mlp_gateup_smoke.problems(env, wrong), 'a log of another configuration is not this arm\'s')
        self.assertTrue([p for p in c2_smoke_check.fusion_problems('nothing\n', env) if 'QWEN_FAST_MLP_CFG=g3u4d3' in p])

    def test_the_upload_levers_and_the_shard_argmax_fold_parse(self):
        import qwen_device_zeros
        import qwen_lazy_shard
        import tp4_shard_argmax

        for name, environ in self.environments():
            with self.subTest(profile=name):
                self.assertEqual(qwen_device_zeros.flag_problems(environ), [])
                self.assertEqual(qwen_lazy_shard.flag_problems(environ), [])
                self.assertTrue(qwen_device_zeros.enabled(environ))
                self.assertTrue(qwen_lazy_shard.enabled(environ))
                self.assertTrue(tp4_shard_argmax.fold2_enabled(environ))
                self.assertEqual(qwen_device_zeros.audited(environ), name == AUDITED)

    def test_the_page_writer_is_on_with_its_recorded_proof_and_the_fused_mlp_stays_off(self):
        import kv_page_writer_tp4

        block = json.loads((HERE / 'ordered_writer_evidence_tp4.json').read_text(encoding='utf-8'))['page_writer']
        self.assertEqual((block['status'], block['scope'], block['failures']), ('PASS', 'full', 0), 'the card-M proof is recorded')
        for name, environ in self.environments():
            with self.subTest(profile=name):
                self.assertTrue(kv_page_writer_tp4.enabled(environ))
                self.assertEqual(kv_page_writer_tp4._read(kv_page_writer_tp4.AUDIT_FLAG, environ), name == AUDITED)
                self.assertFalse(environ.get('QWEN_FAST_MLP_GATEUP') not in (None, '0'))
                for width in block['widths']:
                    for source in block['sources']:
                        self.assertEqual(kv_page_writer_tp4.evidence_problems(block['wt'], width, source), [], (width, source))
        with self.assertRaises(ValueError):
            kv_page_writer_tp4.enabled(dict(gate_environment(dict(PROFILES[TIMED], name=TIMED)), QWEN_FAST_TP='2'))          # a TP4 lever at the pair


class RoundHostTests(unittest.TestCase):
    """The round-host levers (tp4/round-host) beside the fusion levers: accepted together, judged by their own smoke rule, and KEYED independent of every fusion lever."""

    FLAGS = ('QWEN_FAST_TP4_ROUND_HOST_SELECT', 'QWEN_FAST_TP4_ROUND_HOST_READ', 'QWEN_FAST_TP4_ROUND_HOST_KEYED', 'QWEN_FAST_TP4_ROUND_HOST_LEAN')

    def test_the_flags_parse_strictly_beside_the_fusion_levers_and_the_audit_is_only_on_the_audited_twin(self):
        import round_host

        for name in (TIMED, AUDITED):
            environ = gate_environment(dict(PROFILES[name], name=name))
            with self.subTest(profile=name):
                state = round_host.parse(environ)
                self.assertEqual([flag for flag in round_host.FLAGS if state[flag]],
                                 [flag for flag in round_host.FLAGS if flag in self.FLAGS or (name == AUDITED and flag == round_host.AUDIT_FLAG)])
                self.assertFalse(state[round_host.LOG_FLAG], 'the ledger comes from LEAN')
                self.assertTrue(round_host.requested(environ))
        base = gate_environment(dict(PROFILES[TIMED], name=TIMED))
        for flag in self.FLAGS:
            base.pop(flag)
        base['QWEN_FAST_TP4_ROUND_HOST_AUDIT'] = '1'
        with self.assertRaises(ValueError, msg='an audit with no lever is refused: the check is live'):
            round_host.parse(base)

    def test_the_smoke_rule_of_the_round_host_judges_both_twins_by_their_own_flags(self):
        import round_host

        for name in (TIMED, AUDITED):
            env = PROFILES[name]['env']
            problems, _facts = c2_smoke_check.round_host_problems(env, '', False)
            self.assertTrue(any('round host' in problem and 'one needed' in problem for problem in problems), name)
            engaged = '%s %s' % (round_host.ENGAGED_MARKER, ' '.join('%s=%d' % (flag.rsplit('_', 1)[-1].lower(), int(env.get(flag) == '1')) for flag in round_host.FLAGS))
            right, _facts = c2_smoke_check.round_host_problems(env, engaged + '\n', False)
            self.assertFalse([problem for problem in right if 'the engaged line says' in problem], name)
            wrong, _facts = c2_smoke_check.round_host_problems(env, engaged.replace('keyed=1', 'keyed=0') + '\n', False)
            self.assertTrue([problem for problem in wrong if 'keyed=0' in problem], name)

    def test_the_keyed_values_and_the_pre_stage_name_no_fusion_lever(self):
        """KEYED's claim is that every staged value but the tokens is a pure function of (start, page table) per segment. The staged list is packed_values and the pre-stage
        snapshot is verify_prestage; neither reads a fusion lever's flag, so no lever can change a staged value (a lever that did would make the keyed round write stale bytes)."""
        import ast

        flags = set(flag for flag, _value, _engaged, _fell, _what in c2_smoke_check.FUSION_LEVERS) | set(flag + '_AUDIT' for flag, *_rest in c2_smoke_check.FUSION_LEVERS)
        flags |= set(row[0] for row in c2_smoke_check.SAMPDRAFT_LEVERS) | set(row[0] for row in c2_smoke_check.SAMPDRAFT_AUDITS)
        flags |= {'QWEN_FAST_TP4_SHARD_ARGMAX_FOLD2', 'QWEN_FAST_DEVICE_ZEROS', 'QWEN_FAST_LAZY_SHARD_W'}
        self.assertIn('QWEN_FAST_KV_PAGE_WRITER', flags)
        prestage = (HERE / 'verify_prestage.py').read_text(encoding='utf-8')
        self.assertEqual([flag for flag in sorted(flags) if flag in prestage], [])
        tree = ast.parse((HERE / 'packed_verifier.py').read_text(encoding='utf-8'))
        function = next(node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == 'packed_values')
        constants = {node.value for node in ast.walk(function) if isinstance(node, ast.Constant) and isinstance(node.value, str)}
        self.assertEqual(sorted(flags & constants), [])
        names = {node.id for node in ast.walk(function) if isinstance(node, ast.Name)}
        self.assertFalse(names & {'kv_page_writer_tp4', 'draft_fusion_tp', 'tp4_mlp_gateup', 'tp4_shard_argmax', 'ccl_options_tp'})
        keyed = (HERE / 'verify_prestage.py').read_text(encoding='utf-8')
        self.assertIn("__slots__ = ('starts', 'tables', 'readers', 'token_index', 'kv_ok')", keyed)


class SmokeTableTests(unittest.TestCase):
    def rows(self):
        levers = [(flag, value) for flag, value, _engaged, _fell, _what in c2_smoke_check.FUSION_LEVERS]
        levers += [(flag, '1') for flag, *_rest in c2_smoke_check.SAMPDRAFT_LEVERS]
        audits = [flag for flag, _marker, _what in c2_smoke_check.FUSION_AUDITS] + [flag for flag, _marker, _what in c2_smoke_check.SAMPDRAFT_AUDITS]
        return levers, audits

    def test_every_lever_flag_of_the_twins_has_a_smoke_row_at_the_value_it_carries(self):
        levers, audits = self.rows()
        env = PROFILES[AUDITED]['env']
        companions = ('QWEN_FAST_TP4_SHARD_ARGMAX_FOLD2', 'QWEN_FAST_DEVICE_ZEROS', 'QWEN_FAST_LAZY_SHARD_W')     # (judged by their packages' own rules, not the generic tables)
        for flag, value in SWITCHED_ON.items():
            if flag in companions or flag.startswith('QWEN_FAST_TP4_ROUND_HOST_'):      # (the round-host levers: c2_smoke_check.round_host_problems)
                continue
            self.assertIn((flag, value), levers, 'no smoke row judges %s=%s' % (flag, value))
        for flag in AUDIT_FLAGS:
            if flag in ('QWEN_FAST_DEVICE_ZEROS_AUDIT', 'QWEN_FAST_LAZY_SHARD_W_AUDIT', 'QWEN_FAST_TP4_ROUND_HOST_AUDIT'):
                continue
            self.assertIn(flag, audits, 'no smoke row demands an exact=True line for ' + flag)
            self.assertEqual(env[flag], '1')

    def test_the_upload_levers_are_judged_by_the_contract_s_own_smoke_rule(self):
        # (c2_smoke_check.upload_p0_problems reads DEVICE_ZEROS / LAZY_SHARD_W and their audits)
        env = dict(PROFILES[AUDITED]['env'])
        problems = c2_smoke_check.upload_p0_problems(env, '')
        self.assertTrue(any('QWEN_FAST_DEVICE_ZEROS' in problem for problem in problems))
        self.assertTrue(any('QWEN_FAST_LAZY_SHARD_W' in problem for problem in problems))

    def test_a_log_without_any_lever_fails_the_audited_twin_lever_by_lever(self):
        env = PROFILES[AUDITED]['env']
        found = c2_smoke_check.fusion_problems('nothing\n', env)
        for flag in ('QWEN_FAST_DRAFT_PERMUTE', 'QWEN_FAST_DRAFT_REDUCE', 'QWEN_FAST_DRAFT_QKV1', 'QWEN_FAST_DRAFT_TAIL', 'QWEN_FAST_DRAFT_GATEUP1', 'QWEN_FAST_DRAFT_MM_GRID',
                     'QWEN_FAST_DRAFT_HEAD64', 'QWEN_FAST_CCL_OPTIONS', 'QWEN_FAST_MLP_CFG'):
            self.assertTrue(any(flag in problem for problem in found), flag)
        self.assertTrue(any('QWEN_FAST_TP4_SHARD_ARGMAX' in problem for problem in c2_smoke_check.sampdraft_problems('nothing\n', env)))


class ParkedEngineBandTests(unittest.TestCase):
    """The parked-engine DRAM band (parked_judge.ENGINE_GB) is lever-aware for the op-fusion arms and exactly as before for everything else."""

    @staticmethod
    def ledger(each, free_after=4.0, engines=8):
        def line(phase, chip, allocated, free):
            return '[MEMLEDGER] phase=%s point=x chip%d allocated=%.3fGB free=%.3fGB largest_free=%.1fMB total=33.0GB' % (phase, chip, allocated, free, free * 900)
        return '\n'.join([line('P7', chip, 24.78, 8.87) for chip in range(4)] + [line('P7p', chip, 24.78 + engines * each, free_after) for chip in range(4)]) + '\n'

    @staticmethod
    def took(env, text):
        return [problem for problem in c2_smoke_check.parked_container_problems(env, text)[0] if 'parked engines took' in problem]

    def test_only_the_fusion_arms_get_the_lever_band_and_production_keeps_its_own(self):
        import parked_judge

        for name, profile in PROFILES.items():
            if profile['env'].get('QWEN_FAST_PARKED_ENGINES') != '1':
                continue                    # the band is only judged for an arm that parks engines (the older S1 profiles never do)
            levers, audits = c2_smoke_check.fusion_arm_flags(profile['env'])
            band = parked_judge.engine_band(levers, audits)
            twin = name.startswith(fusion.NAMESPACE) or name in fusion.twin_names()
            with self.subTest(profile=name):
                if not twin:
                    self.assertEqual((levers, audits, band), ([], [], parked_judge.ENGINE_GB))
                else:
                    self.assertNotEqual(band, parked_judge.ENGINE_GB)
        self.assertEqual(parked_judge.ENGINE_GB, (0.46, 0.51))
        self.assertEqual(c2_smoke_check.fusion_arm_flags(None), ([], []))
        self.assertEqual(c2_smoke_check.fusion_arm_flags(dict(PARENT['env'], QWEN_FAST_DRAFT_REDUCE='0')), ([], []))

    def test_the_measured_combined_arm_passes_and_the_same_reading_still_fails_production(self):
        # run v714 and v716: 3.346 GB for eight engines on every chip (0.418 each) failed the production band 3.68-4.08 and is the lever arm's measurement
        reading = self.ledger(3.346 / 8)
        self.assertEqual(self.took(PROFILES[TIMED]['env'], reading), [])
        failed = self.took(PARENT['env'], reading)
        self.assertEqual(len(failed), 4)
        self.assertTrue(all('3.346' in problem and '3.68-4.08' in problem for problem in failed))

    def test_the_lever_arm_keeps_the_production_ceiling_and_has_a_floor(self):
        env = PROFILES[TIMED]['env']
        self.assertEqual(self.took(env, self.ledger(0.495)), [])                      # the production engine is within the lever band
        self.assertEqual(len(self.took(env, self.ledger(0.52))), 4)                   # a lever that ADDS DRAM is not absorbed
        self.assertEqual(len(self.took(env, self.ledger(0.37))), 4)                   # an engine that is not the whole captured graph is not either
        self.assertTrue(any('op-fusion lever arm' in problem for problem in self.took(env, self.ledger(0.52))))
        self.assertEqual(self.took(PARENT['env'], self.ledger(0.48)), [])
        self.assertEqual(len(self.took(PARENT['env'], self.ledger(0.418))), 4)

    def test_a_single_lever_twin_lies_between_the_production_engine_and_the_whole_set(self):
        for name in fusion.twin_names():
            if name in (TIMED, AUDITED) or name.endswith('-audit'):
                continue
            env = PROFILES[name]['env']
            if not c2_smoke_check.fusion_arm_flags(env)[0]:
                continue
            with self.subTest(profile=name):
                self.assertEqual(self.took(env, self.ledger(0.418)), [])
                self.assertEqual(self.took(env, self.ledger(0.48)), [])

    def test_an_audited_lever_arm_has_no_ceiling_but_the_free_dram_floor_binds(self):
        env = PROFILES[AUDITED]['env']
        self.assertEqual(self.took(env, self.ledger(0.8, free_after=3.7)), [])
        self.assertEqual(len(self.took(env, self.ledger(0.37, free_after=3.7))), 4)
        floor = [problem for problem in c2_smoke_check.parked_container_problems(env, self.ledger(0.8, free_after=3.0))[0] if 'floor' in problem]
        self.assertEqual(len(floor), 4)
        facts = c2_smoke_check.parked_container_problems(env, self.ledger(0.8, free_after=3.7))[1]
        self.assertEqual(facts['engine_gb'], {0: 0.8, 1: 0.8, 2: 0.8, 3: 0.8})        # the first completed audited run prints the figure that sets its ceiling


class CombinedPackTests(unittest.TestCase):
    NAMES = ('B0-build', 'X0-status-rescan-reset', 'FXA-all-audited-attach', 'FXC1-all-control-timed', 'FXL1-all-lever-timed', 'FXC2-all-control-repeat',
             'FXL2-all-lever-repeat', 'Z-reset')

    def values(self, name):
        return job.parse_env((PACK / (name + '.env')).read_text(encoding='utf-8'))

    def test_the_pack_is_what_the_generator_makes(self):
        wanted = jobs_gen.generate(PLAN, jobs_gen.FOLDER)
        mine = {name: text for name, text in wanted.items() if name.startswith('combined/')}
        self.assertEqual(sorted(mine), sorted(['combined/%s.env' % name for name in self.NAMES] + ['combined/ORDER.txt']))
        self.assertEqual(jobs_gen.stale(jobs_gen.FOLDER, wanted), [])

    def test_the_order_lists_the_templates_once_in_the_asked_order_on_the_one_image(self):
        lines = [line.split() for line in (PACK / 'ORDER.txt').read_text(encoding='utf-8').splitlines() if line.strip() and not line.startswith('#')]
        self.assertEqual([line[0] for line in lines], list(self.NAMES))
        self.assertEqual({line[2] for line in lines}, {jobs_gen.IMAGE})
        self.assertEqual([line[1] for line in lines], ['stop', 'stop'] + ['soft'] * 6)

    def test_the_audited_attach_runs_the_audited_twin_and_the_abab_is_control_lever_control_lever(self):
        self.assertEqual(self.values('FXA-all-audited-attach')['C2_PROFILE'], AUDITED)
        self.assertEqual([self.values(name)['C2_PROFILE'] for name in self.NAMES[3:7]], [fusion.PARENT, TIMED, fusion.PARENT, TIMED])

    def test_the_tests_are_the_per_lever_packs_and_include_concurrent8_steady(self):
        for name in self.NAMES[2:7]:
            self.assertEqual(self.values(name)['C2_SMOKE_TESTS'], 'warmup,concurrent8_steady', name)
        per_lever = job.parse_env((HERE / 'references' / 'fusion-jobs' / 'S1C1-s1-control-timed.env').read_text(encoding='utf-8'))
        self.assertEqual(per_lever['C2_SMOKE_TESTS'], self.values('FXC1-all-control-timed')['C2_SMOKE_TESTS'])

    def test_the_needs_gate_the_timed_pair_on_the_audit_and_the_control(self):
        needs = dict(line[len('# NEEDS '):].split(' <- ') for line in (PACK / 'ORDER.txt').read_text(encoding='utf-8').splitlines() if line.startswith('# NEEDS '))
        self.assertEqual(needs['FXL1'], 'FXA FXC1')
        self.assertEqual((needs['FXA'], needs['FXC1'], needs['FXC2'], needs['FXL2']), ('X0', 'X0', 'FXL1', 'FXC2'))

    def test_the_templates_name_the_reader_command_and_every_lever_the_audit_is_judged_by(self):
        text = ' '.join(line.lstrip('# ') for line in (PACK / 'FXL1-all-lever-timed.env').read_text(encoding='utf-8').splitlines())        # the generator wraps comment lines
        self.assertIn('python3 scripts/ci/w2ln_timing_compare.py pair <A container log> <B container log> --window steady --a-smoke <A smoke log> --b-smoke <B smoke log>', text)
        audit = (PACK / 'FXA-all-audited-attach.env').read_text(encoding='utf-8')
        for lever in PLAN['levers']:
            if lever['id'] in SPEC['levers']:
                self.assertIn(lever['flag'], audit)
        for word in ('exact=True', 'no fell-back line', "no 'audit mismatch'", 'EVERY lever\'s rule'):
            self.assertIn(word, audit)

    def test_the_audited_attach_and_the_four_timed_jobs_run_the_telemetry_sidecar_and_the_rest_do_not(self):
        keyed = {name: [line for line in (PACK / (name + '.env')).read_text(encoding='utf-8').splitlines() if line == 'C2_TELEMETRY=1'] for name in self.NAMES}
        for name in ('FXA-all-audited-attach', 'FXC1-all-control-timed', 'FXL1-all-lever-timed', 'FXC2-all-control-repeat', 'FXL2-all-lever-repeat'):
            self.assertEqual(keyed[name], ['C2_TELEMETRY=1'], name)
            outputs = job.read_job(self.values(name), job.profile_names(str(HERE / 'qwen_c2_profiles.json')), envs=job.profile_envs(str(HERE / 'qwen_c2_profiles.json')))
            self.assertEqual(outputs['telemetry'], '1', name)
        for name in ('B0-build', 'X0-status-rescan-reset', 'Z-reset'):
            self.assertEqual(keyed[name], [], name)
        self.assertEqual(set(keyed) - {'B0-build', 'X0-status-rescan-reset', 'Z-reset'}, {name for name, lines in keyed.items() if lines}, 'only the arms carry it')

    def test_every_template_exits_zero_through_the_job_reader_and_the_command_line(self):
        profiles = job.profile_names(str(HERE / 'qwen_c2_profiles.json'))
        envs = job.profile_envs(str(HERE / 'qwen_c2_profiles.json'))
        for name in self.NAMES:
            with self.subTest(name):
                outputs = job.read_job(self.values(name), profiles, envs=envs)
                self.assertTrue(outputs['actions'])
                result = subprocess.run([sys.executable, '-s', str(HERE / 'c2_serving_job.py'), str(PACK / (name + '.env')), str(HERE / 'qwen_c2_profiles.json')],
                                        stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=str(HERE.parent.parent))
                self.assertEqual(result.returncode, 0, result.stderr.decode('utf-8', 'replace'))

    def test_the_per_lever_order_points_at_the_combined_pack_as_the_one_that_runs_first(self):
        text = (HERE / 'references' / 'fusion-jobs' / 'ORDER.txt').read_text(encoding='utf-8')
        self.assertIn('THE COMBINED PACK (references/fusion-jobs/combined', text)
        self.assertIn('runs FIRST; this ORDER is the ablation', text)

    def test_the_package_folders_of_the_per_lever_order_do_not_list_the_generators_own_combined_folder(self):
        self.assertNotIn('fusion-jobs/combined', ' '.join(jobs_gen.package_folders(jobs_gen.FOLDER)))


if __name__ == '__main__':
    unittest.main()
